In [632]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [633]:
# Load Datasets
cust_df = pd.read_excel('raw_data\Cust_DS.xlsx', sheet_name = 'DATASET', parse_dates=True)
print('customers dataset loaded!')
erms_df = pd.read_excel('raw_data\ERMS_DS.xlsx', sheet_name = 'DATASET', parse_dates=True)
print('ERMS dataset loaded!')

# Set display options
pd.set_option('display.width', 2000)
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.max_info_columns', 200)
pd.option_context('display.max_columns', 200)

customers dataset loaded!
ERMS dataset loaded!

In [634]:
cust_df.sample(3)

    اقرار الموافقة                                قم باخذ الموقع  _قم باخذ الموقع_latitude  _قم باخذ الموقع_longitude  _قم باخذ الموقع_altitude  _قم باخذ الموقع_precision    اسم الماسح تاريخ المسح Governorate District: Abyan  ... Does […] business/vendor help you save time, money, effort, other?                                                       (please explain) Column3 What is the impact of such projects in your area that contributes to the best use of resources?(please explain) Column4                           What recommendations do you have for supporting businesses in your community?   Column5  what goods/services do you wish were available in your community?  Column6  _index
115            نعم    13.04773 44.9309985 69.86480712890625 4.63                 13.047730                  44.930999                 69.864807                      4.630      فهد عادل  2020-12-17        Lahj             NaN  ...                                                                Yes                             بسبب قرب المسافة وتوفير المال حق المواصلات     NaN                                                                          تاثير ايجابي  يسبب الازدهار في المنطقة     NaN                                                                                                  مولات،       NaN                        مسجد، مدرسة ، تصليح المجاري ، تصليح الطرقات      NaN     116
130            نعم  13.6382277 45.313068 1461.012451171875 4.424                 13.638228                  45.313068               1461.012451                      4.424  طلال عبدالله  2020-12-17       Abyan           Sarar  ...                                                                Yes  بسبب توفير المواد الغذائية والمطلوبة الى المنطقة وهذا يسهل علينا كثير     NaN                                   تحسين المعيشة وتبسيط نقل المواد الى المنطقة حيث التاجر يقوم بتوفير كل ما يلزم     NaN  استمرار الدعم من أجل تيسير المواد الغذائية الأساسية للمواطن وإستفادة التجار من التجارة عبر توسع أعمالهم      NaN                                                      الغاز المنزلي      NaN     131
256            نعم     13.1213387 44.8507139 194.091796875 4.931                 13.121339                  44.850714                194.091797                      4.931     ياسر شفيق  2020-12-29        Lahj             NaN  ...                                                                Yes                                                    جيران في نفس الحارة     NaN                                                اتاحت للنساء عرض بضائع مختلفة وفي متناول ايديهم بسبب قرب المسافة     NaN                                               محلات لبيع الخضار والفواكه ومحلات عطور وتجميل ومحلات اقمشة      NaN    سوق صغير يشمل احتياجات الناس الاساسية وتوفير خدمة الماء للمنطقة      NaN     257

[3 rows x 53 columns]

In [635]:
cust_df.drop(columns=['قم باخذ الموقع', 'اقرار الموافقة', 'اسم الماسح'], inplace=True)

In [636]:
cust_df.columns.to_list()

['_قم باخذ الموقع_latitude',
 '_قم باخذ الموقع_longitude',
 '_قم باخذ الموقع_altitude',
 '_قم باخذ الموقع_precision',
 'تاريخ المسح',
 'Governorate',
 'District: Abyan',
 'District: Lahj',
 'District: Aldalea',
 'Village',
 "Respondent's name",
 'Have you noticed any difference in any of product/service  availability in the area after the conflict?',
 'If yes, can you mention in which domain/sector',
 ' Provision of household needs',
 'Other',
 'Food provision',
 'Construction services',
 'Other: Detail',
 'Did you deal with/ purchasing with business owner supported by ADRA intervention before?',
 'If so, who is it?',
 'What was different about the business of this person you notice 2 years ago compared to now?',
 'Column1',
 'Were you satisfied with the product/service that […] provide?',
 'If you were not satisfied with the vendor’s services/products, what were the reasons? Please select all that apply.',
 '\uf035 Bad quality of product',
 '\uf035 Bad Dealing',
 'Other2',
 ' detail2',
 'What do you like about […] business/vendor?',
 '5\xa0 Good Quality of work',
 '\uf035 Unique of the products/ service',
 '\uf035 Good dealing',
 '\uf035 Ease of access',
 'Other4',
 'Good price',
 'Other: detail3',
 'Other: detail4',
 'If you no longer have access to […] shop(s) would you be impacted?',
 'If yes, how? (please explain)',
 'Column2',
 'Does […] business/vendor help you save time, money, effort, other?',
 ' (please explain)',
 'Column3',
 'What is the impact of such projects in your area that contributes to the best use of resources?(please explain)',
 'Column4',
 'What recommendations do you have for supporting businesses in your community? ',
 'Column5',
 'what goods/services do you wish were available in your community?',
 'Column6',
 '_index']

In [637]:
cust_df.columns[23:].to_list()

['If you were not satisfied with the vendor’s services/products, what were the reasons? Please select all that apply.',
 '\uf035 Bad quality of product',
 '\uf035 Bad Dealing',
 'Other2',
 ' detail2',
 'What do you like about […] business/vendor?',
 '5\xa0 Good Quality of work',
 '\uf035 Unique of the products/ service',
 '\uf035 Good dealing',
 '\uf035 Ease of access',
 'Other4',
 'Good price',
 'Other: detail3',
 'Other: detail4',
 'If you no longer have access to […] shop(s) would you be impacted?',
 'If yes, how? (please explain)',
 'Column2',
 'Does […] business/vendor help you save time, money, effort, other?',
 ' (please explain)',
 'Column3',
 'What is the impact of such projects in your area that contributes to the best use of resources?(please explain)',
 'Column4',
 'What recommendations do you have for supporting businesses in your community? ',
 'Column5',
 'what goods/services do you wish were available in your community?',
 'Column6',
 '_index']

In [638]:
column_mapper = {
    '_قم باخذ الموقع_latitude': 'latitude',
 '_قم باخذ الموقع_longitude': 'longitude',
 '_قم باخذ الموقع_altitude': 'altitude',
 '_قم باخذ الموقع_precision': 'precision',
 'تاريخ المسح': 'survey_date',
 'Governorate': 'governorate',
 'District: Abyan':'district_abyan',
 'District: Lahj':'district_lahj',
 'District: Aldalea':'district_aldalea',
 'Village':'village',
 "Respondent's name":"respondent_name",
 'Have you noticed any difference in any of product/service  availability in the area after the conflict?':'product_service_difference',
 'If yes, can you mention in which domain/sector': 'sector',
 ' Provision of household needs': 'sector_household_needs',
 'Other': 'product_service_difference_sector',
 'Food provision': 'sector_food_provision',
 'Construction services': 'sector_construction_services',
 'Other: Detail': 'sector_other',
 'Did you deal with/ purchasing with business owner supported by ADRA intervention before?':'dealt_with_business_owner',
 'If so, who is it?':'business_owner',
 'What was different about the business of this person you notice 2 years ago compared to now?':'business_owner_difference1', # To Drop, duplicate information
 'Column1': 'business_owner_difference',
 'Were you satisfied with the product/service that […] provide?':'satisfied_with_product_service',
 'If you were not satisfied with the vendor’s services/products, what were the reasons? Please select all that apply.': 'reason_dissatisfaction',
 '\uf035 Bad quality of product': 'bad_quality_product',
  '\uf035 Bad Dealing': 'bad_treatment',
 'Other2': 'dissatisfaction_reason_other',
 ' detail2': 'dissatisfaction_reason_other_detail',
 'What do you like about […] business/vendor?': 'like_business_vendor',
 '5\xa0 Good Quality of work': 'good_quality_work',
 '\uf035 Unique of the products/ service': 'unique_product_service',
 '\uf035 Good dealing': 'good_treatment',
 '\uf035 Ease of access': 'ease_of_access',
 'Other4': 'like_business_vendor_other',
 'Good price': 'good_price',
 'Other: detail3': 'like_business_vendor_other_detail1', # To Drop, duplicate information
 'Other: detail4': 'like_business_vendor_other_detail',
 'If you no longer have access to […] shop(s) would you be impacted?':'no_longer_access_impacted',
 'If yes, how? (please explain)': 'no_longer_access_impacted_how1', # To Drop, duplicate information
 'Column2': 'no_longer_access_impacted_how',
 'Does […] business/vendor help you save time, money, effort, other?': 'business_vendor_help_time_money_effort',
 ' (please explain)': 'business_vendor_help_time_money_effort_explain1', # To Drop, duplicate information
 'Column3': 'business_vendor_help_time_money_effort_explain',
 'What is the impact of such projects in your area that contributes to the best use of resources?(please explain)': 'impact_projects_resources',
 'Column4': 'impact_projects_resources_explain',
 'What recommendations do you have for supporting businesses in your community? ':'recommendations_businesses_community',
 'Column5': 'recommendations_businesses_community_explain',
 'what goods/services do you wish were available in your community?': 'goods_services_community',
 'Column6': 'goods_services_community_explain'
}

In [639]:
cust_df.rename(columns={'product_service_difference_sector': 'sector_other'}, inplace=True)

In [640]:
cust_df.rename(columns=column_mapper, inplace=True)

In [641]:
cust_df.drop(columns=['business_owner_difference1', 
'like_business_vendor_other_detail1', 
'no_longer_access_impacted_how1', 
'business_vendor_help_time_money_effort_explain1'], 
inplace=True)

In [642]:
cust_df.columns

Index(['latitude', 'longitude', 'altitude', 'precision', 'survey_date', 'governorate', 'district_abyan', 'district_lahj', 'district_aldalea', 'village', 'respondent_name', 'product_service_difference', 'sector', 'sector_household_needs', 'product_service_difference_sector', 'sector_food_provision', 'sector_construction_services', 'sector_other', 'dealt_with_business_owner', 'business_owner', 'business_owner_difference', 'satisfied_with_product_service', 'reason_dissatisfaction', 'bad_quality_product', 'bad_treatment', 'dissatisfaction_reason_other', 'dissatisfaction_reason_other_detail', 'like_business_vendor', 'good_quality_work', 'unique_product_service', 'good_treatment', 'ease_of_access', 'like_business_vendor_other', 'good_price', 'like_business_vendor_other_detail', 'no_longer_access_impacted', 'no_longer_access_impacted_how', 'business_vendor_help_time_money_effort', 'business_vendor_help_time_money_effort_explain', 'impact_projects_resources', 'impact_projects_resources_explain', 'recommendations_businesses_community', 'recommendations_businesses_community_explain', 'goods_services_community', 'goods_services_community_explain', '_index'], dtype='object')

In [643]:
cust_df.shape

(330, 46)

In [644]:
cust_df['survey_date'] = pd.to_datetime(cust_df['survey_date'])
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 46 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   latitude                                        316 non-null    float64
 1   longitude                                       316 non-null    float64
 2   altitude                                        316 non-null    float64
 3   precision                                       316 non-null    float64
 4   survey_date                                     330 non-null    datetime64[ns]
 5   governorate                                     330 non-null    object
 6   district_abyan                                  183 non-null    object
 7   district_lahj                                   121 non-null    object
 8   district_aldalea                                26 non-null     object
 9   village                                         330 non-null    object
 10  respondent_name                                 330 non-null    object
 11  product_service_difference                      330 non-null    object
 12  sector                                          271 non-null    object
 13  sector_household_needs                          271 non-null    float64
 14  product_service_difference_sector               248 non-null    float64
 15  sector_food_provision                           138 non-null    float64
 16  sector_construction_services                    138 non-null    float64
 17  sector_other                                    16 non-null     object
 18  dealt_with_business_owner                       330 non-null    object
 19  business_owner                                  330 non-null    object
 20  business_owner_difference                       330 non-null    object
 21  satisfied_with_product_service                  330 non-null    object
 22  reason_dissatisfaction                          4 non-null      object
 23  bad_quality_product                             4 non-null      float64
 24  bad_treatment                                   4 non-null      float64
 25  dissatisfaction_reason_other                    4 non-null      float64
 26  dissatisfaction_reason_other_detail             2 non-null      object
 27  like_business_vendor                            326 non-null    object
 28  good_quality_work                               326 non-null    float64
 29  unique_product_service                          326 non-null    float64
 30  good_treatment                                  326 non-null    float64
 31  ease_of_access                                  326 non-null    float64
 32  like_business_vendor_other                      326 non-null    float64
 33  good_price                                      163 non-null    float64
 34  like_business_vendor_other_detail               6 non-null      object
 35  no_longer_access_impacted                       330 non-null    object
 36  no_longer_access_impacted_how                   5 non-null      object
 37  business_vendor_help_time_money_effort          330 non-null    object
 38  business_vendor_help_time_money_effort_explain  4 non-null      object
 39  impact_projects_resources                       330 non-null    object
 40  impact_projects_resources_explain               9 non-null      object
 41  recommendations_businesses_community            330 non-null    object
 42  recommendations_businesses_community_explain    5 non-null      object
 43  goods_services_community                        330 non-null    object
 44  goods_services_community_explain                5 non-null      object
 45  _index                                          330 non-null    int64
dtypes: datetime64[ns](1), float64(17), int64(1), object(27)
memory usage: 118.7+ KB

In [645]:
cust_df.columns

Index(['latitude', 'longitude', 'altitude', 'precision', 'survey_date', 'governorate', 'district_abyan', 'district_lahj', 'district_aldalea', 'village', 'respondent_name', 'product_service_difference', 'sector', 'sector_household_needs', 'product_service_difference_sector', 'sector_food_provision', 'sector_construction_services', 'sector_other', 'dealt_with_business_owner', 'business_owner', 'business_owner_difference', 'satisfied_with_product_service', 'reason_dissatisfaction', 'bad_quality_product', 'bad_treatment', 'dissatisfaction_reason_other', 'dissatisfaction_reason_other_detail', 'like_business_vendor', 'good_quality_work', 'unique_product_service', 'good_treatment', 'ease_of_access', 'like_business_vendor_other', 'good_price', 'like_business_vendor_other_detail', 'no_longer_access_impacted', 'no_longer_access_impacted_how', 'business_vendor_help_time_money_effort', 'business_vendor_help_time_money_effort_explain', 'impact_projects_resources', 'impact_projects_resources_explain', 'recommendations_businesses_community', 'recommendations_businesses_community_explain', 'goods_services_community', 'goods_services_community_explain', '_index'], dtype='object')

In [646]:
# Convert to 1 if has content, 0 if empty/NaN
cust_df['sector_other'] = cust_df['sector_other'].apply(
    lambda x: 1 if pd.notna(x) and str(x).strip() != '' else 0
)

print("✓ sector_other converted to binary:")
print(cust_df['sector_other'].value_counts())

✓ sector_other converted to binary:
sector_other
0    314
1     16
Name: count, dtype: int64

In [647]:
cust_df.drop(columns=['sector'], inplace=True)

In [648]:
# Create a demographic (or meta) variable list from the dataframe

cust_demo_var = ['latitude', 'longitude', 'altitude', 'precision', 'survey_date',
       'governorate', 'district', 'village', 'respondent_id']

In [649]:
# Create a multiple response variable list from the dataframe
cust_mr_var = ['sector_household_needs', 'sector_other', 'sector_food_provision',
       'sector_construction_services', 'bad_quality_product', 'bad_treatment',
       'dissatisfaction_reason_other', 'good_quality_work',
       'unique_product_service', 'good_treatment', 'ease_of_access', 'like_business_vendor_other',
       'good_price']

In [650]:
# Create a single response variable list from the dataframe
cust_sr_var = ['product_service_difference', 'dealt_with_business_owner', 
       'business_owner_difference', 'satisfied_with_product_service', 
       'no_longer_access_impacted',
       'business_vendor_help_time_money_effort'
       ]

In [651]:
cust_mr_var_oe = ['like_business_vendor_other_detail', 'dissatisfaction_reason_other_detail']
cust_sr_var_oe = ['no_longer_access_impacted_how', 'recommendations_businesses_community',
       'recommendations_businesses_community_explain','goods_services_community', 
       'goods_services_community_explain', 'business_vendor_help_time_money_effort_explain', 
       'impact_projects_resources_explain', 'business_owner', 'impact_projects_resources'
       ]

In [652]:
# Check what columns contain 'district'
district_cols = [col for col in cust_df.columns if 'district' in col.lower()]
print("District-related columns:")
print(district_cols)

District-related columns:
['district_abyan', 'district_lahj', 'district_aldalea']

In [653]:
# Create 'district' column that merges the three other columns
cust_df['district'] = cust_df['district_abyan'].fillna(cust_df['district_aldalea'].fillna(cust_df['district_lahj']))

In [654]:
# Check what columns contain 'district'
district_cols = [col for col in cust_df.columns if 'district' in col.lower()]
print("District-related columns:")
print(district_cols)
cust_df[['governorate', 'district']]

District-related columns:
['district_abyan', 'district_lahj', 'district_aldalea', 'district']

    governorate district
0          Lahj   Radfan
1          Lahj   Radfan
2          Lahj   Radfan
3          Lahj   Radfan
4          Lahj   Radfan
..          ...      ...
325       Abyan  Khanfir
326       Abyan  Khanfir
327       Abyan  Khanfir
328       Abyan  Khanfir
329       Abyan  Khanfir

[330 rows x 2 columns]

In [655]:
# Drop old district columns
cust_df.drop(columns=['district_abyan', 'district_lahj', 'district_aldalea'], inplace=True)

# Get index of governorate column
gov_idx = cust_df.columns.get_loc('governorate')
cols_before = cust_df.columns[:gov_idx+1].tolist()
cols_after = [c for c in cust_df.columns[gov_idx+1:] if c not in ['district']]

# Reorder
cust_df = cust_df[cols_before + ['district'] + cols_after]

In [656]:
# Determine the number of rows in the DataFrame
num_rows = len(cust_df)

# Generate the numerical sequence (e.g., [1, 2, 3, ... N])
sequence = np.arange(1, num_rows + 1)

# FIX APPLIED HERE: Use np.char.zfill()
# a) Convert the sequence array to strings first
sequence_str = sequence.astype(str)

# b) Apply zero-filling using np.char.zfill()
padded_sequence = np.char.zfill(sequence_str, 3)

# c) Prepend 'R' (NumPy supports string concatenation on arrays)
new_respondent_ids = 'R' + padded_sequence 

# Assign the new IDs back to the column
cust_df['respondent_name'] = new_respondent_ids 
# OR
# cust_df['respondent_name'] = new_respondent_ids

cust_df.rename(columns={'respondent_name': 'respondent_id'}, inplace=True)
cust_df['respondent_id']

0      R001
1      R002
2      R003
3      R004
4      R005
       ...
325    R326
326    R327
327    R328
328    R329
329    R330
Name: respondent_id, Length: 330, dtype: object

In [657]:
cust_df_sr = cust_df[cust_demo_var + cust_sr_var]
cust_df_mr = cust_df[cust_demo_var + cust_mr_var]

In [658]:
cust_df_mr.columns

Index(['latitude', 'longitude', 'altitude', 'precision', 'survey_date', 'governorate', 'district', 'village', 'respondent_id', 'sector_household_needs', 'sector_other', 'sector_food_provision', 'sector_construction_services', 'bad_quality_product', 'bad_treatment', 'dissatisfaction_reason_other', 'good_quality_work', 'unique_product_service', 'good_treatment', 'ease_of_access', 'like_business_vendor_other', 'good_price'], dtype='object')

In [659]:
cust_df_sr.columns

Index(['latitude', 'longitude', 'altitude', 'precision', 'survey_date', 'governorate', 'district', 'village', 'respondent_id', 'product_service_difference', 'dealt_with_business_owner', 'business_owner_difference', 'satisfied_with_product_service', 'no_longer_access_impacted', 'business_vendor_help_time_money_effort'], dtype='object')

In [660]:
# Melt multiple response questions
cust_sr_melted = pd.melt(
cust_df_sr,
id_vars=cust_demo_var,
var_name='question',
value_name='response'
)

In [661]:
cust_sr_melted.dropna(subset=['response'], inplace=True)

In [662]:
cust_sr_melted.shape

(1980, 11)

In [663]:
cust_df_mr.columns

Index(['latitude', 'longitude', 'altitude', 'precision', 'survey_date', 'governorate', 'district', 'village', 'respondent_id', 'sector_household_needs', 'sector_other', 'sector_food_provision', 'sector_construction_services', 'bad_quality_product', 'bad_treatment', 'dissatisfaction_reason_other', 'good_quality_work', 'unique_product_service', 'good_treatment', 'ease_of_access', 'like_business_vendor_other', 'good_price'], dtype='object')

In [664]:
# Melt multiple response questions
cust_mr_melted = pd.melt(
cust_df_mr,
id_vars=cust_demo_var,
var_name='question',
value_name='response'
)

In [665]:
cust_mr_melted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4290 entries, 0 to 4289
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   latitude       4108 non-null   float64
 1   longitude      4108 non-null   float64
 2   altitude       4108 non-null   float64
 3   precision      4108 non-null   float64
 4   survey_date    4290 non-null   datetime64[ns]
 5   governorate    4290 non-null   object
 6   district       4290 non-null   object
 7   village        4290 non-null   object
 8   respondent_id  4290 non-null   object
 9   question       4290 non-null   object
 10  response       2682 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(5)
memory usage: 368.8+ KB

In [666]:
cust_mr_melted.dropna(subset=['response'], inplace=True)
cust_sr_melted.dropna(subset=['response'], inplace=True)

In [667]:
cust_df.sample(5)

      latitude  longitude    altitude  precision survey_date governorate  district   village respondent_id product_service_difference  ...  no_longer_access_impacted_how  business_vendor_help_time_money_effort  business_vendor_help_time_money_effort_explain                                                                                                                              impact_projects_resources  impact_projects_resources_explain                                recommendations_businesses_community recommendations_businesses_community_explain                                 goods_services_community goods_services_community_explain _index
154  13.134137  45.374050   20.616150      4.716  2020-12-20       Abyan  Zingibar   الطميسي          R155                        Yes  ...                            NaN                                     Yes                                             NaN  تشغيل الأيادي العاملة المتوقفة وخلق مصادر دخل للأشخاص اللذين هم بلا أعمال\nالقدرة على الشراء بسبب صبر البائعين على الدين ومواقعهم المناسبة في المنطقة                                NaN  دعم بقية الناس ومحاولة النهوض بهم من اجل تخفيض معدل الفقر والبطالة                                          NaN                                        توفير مواد البناء                              NaN    155
177  13.526891  44.851886  654.460693      4.288  2020-12-20        Lahj    Radfan  الحبيلين          R178                        Yes  ...                            NaN                                      No                                             NaN                                                                                                                         ثاتير ايجابي في ازدهار المنطقة                                NaN                                             فتح محلات ومراكز مولات                                           NaN  الخدمات: منتزهات للاطفال _اصلاح الطرقات_ الماء _كهرباء_                              NaN    178
280  13.129765  45.370889    7.331879      4.347  2020-12-30       Abyan  Zingibar    عمودية          R281                    No Idea  ...                            NaN                                     Yes                                             NaN                                                                                                    تعليم الحرفه وتوفير الادوات اللازمة للنساء المهمشات                                NaN                                توفير مساحات ومراكز للأعمال التجارية                                          NaN            النظافة والصرف الصحي وتأهيل النساء لسوق العمل                              NaN    281
141  13.526910  44.851796  639.733398      4.900  2020-12-20        Lahj    Radfan  الحبيلين          R142                        Yes  ...                            NaN                                     Yes                                             NaN                                                                                                                                        انتعاش المنطقه                                 NaN                    محلات صيانه هواتف كبير وجوده عمال\nتموينات كبير                                           NaN                 المجاري من أجل مياه الصرف الصحي\nالمياه                               NaN    142
113  13.018225  44.885805   93.446533      4.029  2020-12-17        Lahj     Tuban    المحلة          R114                        Yes  ...                            NaN                                     Yes                                             NaN                                                                                                                    قربوا لنا المسافة بدل ما نروح للسوق                                NaN                              زش عارفة كل شيء موجود هنا بس مش بكثرة                                           NaN         الكهرباء والماء والصرف الصحي والمواصلات الداخلية                              NaN    114

[5 rows x 43 columns]

In [668]:
erms_df.columns.tolist()

['اقرار الموافقة',
 'اسم الماسح',
 'قم باخذ الموقع',
 '_قم باخذ الموقع_latitude',
 '_قم باخذ الموقع_longitude',
 '_قم باخذ الموقع_altitude',
 '_قم باخذ الموقع_precision',
 'تاريخ المسح',
 'المحافظة',
 'المديرية: ابين',
 'المديرية: لحج',
 'المديرية: الضالع',
 'القرية',
 'اسم المستجيب',
 'ماهي نوع الخدمة او الصنعة التي تقدمها',
 'منذ متى وأنت تدير عملك الذي تم دعمه / تتعامل مع ADRA؟',
 'ما هي مصادر دخلك؟ يرجى اختيار كل ما ينطبق.',
 'ما هي مصادر دخلك؟ يرجى اختيار كل ما ينطبق. 2',
 'ما هي مصادر دخلك؟ يرجى اختيار كل ما ينطبق. 3',
 'ما هي مصادر دخلك؟ يرجى اختيار كل ما ينطبق. 4',
 'ما هي مصادر دخلك؟ يرجى اختيار كل ما ينطبق. 5',
 'ما الذي تعتبره مصدرًا رئيسيًا',
 'ما هو نطاق(العمل) الجغرافي لمشروعك؟',
 'ما هو نطاق(العمل) الجغرافي لمشروعك؟/على مستوى القرية2',
 'ما هو نطاق(العمل) الجغرافي لمشروعك؟/على مستوى الحي3',
 'ما هو نطاق(العمل) الجغرافي لمشروعك؟/على مستوى المقاطعة4',
 'ما هو نطاق(العمل) الجغرافي لمشروعك؟/على مستوى المحافظة5',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/تجلب المزيد من الأرباح6',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/مهنتي7',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/خبرتي8',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/مهنة العائلة9',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/اعتبر المزود الوحيد لهذه الخدمة بالحي10',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/لا يمكن توفير السلع بسهولة في قريتنا11',
 'لماذا قررت استخدام هذه المهنة؟ ما هو الجيد في ذلك؟/اخرى12',
 'اخرى',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/الجودة',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/تقديم عنصر / خدمة لا يقدمها الآخرون13',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/سعر اقل14',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/البيع بالاجل15',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/موقع مناسب16',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/خدمة مناسبة17',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/الثقة18',
 'ما الذي يميز خدماتك عن نفس البائعين /الحرفيين الآخرين؟/اخرى19',
 'اخرى20',
 'هل أضفت أي عناصر / خدمات جديدة إلى عملك بعد حصولك على منحة ADRA؟',
 'إذا كانت الإجابة بنعم ، يرجى ذكر كل ما ينطبق',
 'إذا كانت الإجابة بنعم ، يرجى ذكر كل ما ينطبق/عمال',
 'إذا كانت الإجابة بنعم ، يرجى ذكر كل ما ينطبق/مواد جديدة21',
 'إذا كانت الإجابة بنعم ، يرجى ذكر كل ما ينطبق/تأجير مخزن او توسع22',
 'لماذا لم تتمكن من إنتاج / توفير من قبل استلام الدعم؟',
 'لماذا لم تتمكن من إنتاج / توفير من قبل استلام الدعم؟2',
 'هل تغير سعر السوق خلال السنتين الماضيتين',
 'إذا كانت الإجابة بنعم ، برأيك ماهو السبب في هذا التغيير؟',
 'إذا كانت الإجابة بنعم ، برأيك ماهو السبب في هذا التغيير؟/عوامل اقتصادية25',
 'إذا كانت الإجابة بنعم ، برأيك ماهو السبب في هذا التغيير؟/تحكم جهات غير حكومية في سوق الصرف26',
 'إذا كانت الإجابة بنعم ، برأيك ماهو السبب في هذا التغيير؟/الاستقرار /الوضع الامني27',
 'هل تغير دخلك (خلال 12 شهرًا الماضية / بعد الأزمة)؟ بسبب الدعم الذي تلقيته؟',
 'اشرح السبب اشرح اجابتك',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟/زيادة في عدد الموظفين',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟/زيادة في صافي الدخل',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟/باضافة اصول جديدة',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟/زيادة في المخزون28',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟/زيادة في عدد الزبائن29',
 'إذا زاد دخلك ، فإلى أي مدى وسعت عملك؟/اخرى30',
 'اخرى31',
 'عدد الافراد (قبل التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد ساعات العمل في اليوم (قبل التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد الايام في الاسبوع (قبل التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد الاشهر بالسنة (قبل التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد الافراد (بعد التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد ساعات العمل في اليوم (بعد التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد الايام في الاسبوع (بعد التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'عدد الاشهر بالسنة (بعد التدخل):في حالة زيادة عدد الموظفين ، كم عدد الأشخاص الذين وظفتهم؟',
 'من قمت بالتوظيف',
 'من قمت بالتوظيف/من افراد الاسرة ',
 'من قمت بالتوظيف/أفراد من خارج العائلة',
 'من قمت بالتوظيف/من افراد الاسرة 32',
 'من قمت بالتوظيف/أفراد من خارج العائلة33',
 'اذا كانت الاجابة من افراد الاسرة, كم عددهم',
 'اذا كانت الاجابة من افراد الاسرة, عدد الساعات باليوم',
 'اذا كانت الاجابة من افراد الاسرة, عدد الايام بالاسبوع',
 'اذا كانت الاجابة من افراد الاسرة, عدد الاشهر بالسنة',
 'اذا كانت الاجابة من خارج افراد العائلة , كم عددهم',
 'اذا كانت الاجابة من خارج افراد العائلة , عدد الساعات ',
 'اذا كانت الاجابة من خارج افراد العائلة ,عدد الايام بالاسبوع ',
 'اذا كانت الاجابة من خارج افراد العائلة ,عدد الاشهر بالسنة ',
 'كيف تقوم بالدفع لهم عادتا',
 'كيف تقوم بالدفع لهم عادتا/بشكل يومي',
 'كيف تقوم بالدفع لهم عادتا/بشكل اسبوعي',
 'كيف تقوم بالدفع لهم عادتا/بشكل شهري',
 ' اذا كانت الاجابة زيادة في عدد الزبائن, كيف قمت بمقابلتهم /جذبهم؟ ',
 'Column1',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/ثقة العميل بي34',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/جودة المواد المتوفرة35',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/توفير ادوات/ خدمات غير متوفرة عند الاخرين36',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/توفير سعر اقل37',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/البيع بالاجل ',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/موقع مناسب38',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/سهولة الوصول39',
 'ما رأيك في سبب اختيارالعملاء لك للتعامل / الشراء معك أكثر من البائعين الآخرين؟/اخرى40',
 'اخرى41',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/الإنفاق على الرعاية الصحية',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/أضيف في توسيع الأعمال42',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/الادخار',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/لغرض التعليم',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/نفقات المنزل',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/نفقات الطعام43',
 'إذا كانت الإجابة هي زيادة الدخل ، فكيف تصرف دخلك من الأرباح؟/اخرى44',
 'اخرى45',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/صعوبات الوصول إلى السوق',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/نقص المواصلات',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/انعدام الأمن',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/المسافة إلى السوق46',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/بيع السلع باسعار منخفظة47',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/تكاليف النقل48',
 ' إذا كان قطاع السوق الخاص بك لا ينمو او في نقصان, ماهي الاسباب ، يرجى تحديد كل ما ينطبق؟/اخرى49',
 'اخرى50',
 'هل لديك مكان عمل مستقل / معين؟',
 'ماهو هذا المكان',
 'اخرى51',
 'كيف تبيع منتجاتك؟',
 'تكاملية التجار مع تجار او مشاريع صغيرة تم دعمها عبر ادرا',
 'هل استخدمت او اشتريت سلعًا أو خدمات من (قائمة ERMS / بائعي الأغذية)؟',
 'إذا كانت الإجابة بنعم ، فما هو الغرض الأساسي من التعامل مع مستفيدي المشاريع  الصغيرة / بائعي المواد الغذائية؟',
 'اخرى52',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟/الجودة',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟/الثقة',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟/تقديم مواد / خدمات لا يقدمها الآخرون53',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟/توفير سعر اقل54',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟/البيع بالآجل55',
 'ما الذي جعلك تتعامل معهم وليس مع غيرهم من التجار؟/اخرى56',
 'اخرى57',
 'كيف تقييم تعاملك معهم',
 'اشرح اجابتك في كل الحالات',
 'هل قاموا بشراء (قائمة ERMS / بائعي الأغذية) سلعًا أو خدمات من عملك؟',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟/الجودة58',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟/الثقة59',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟/تقديم مواد / خدمات لا يقدمها الآخرون60',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟/سعر اقل61',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟/البيع بالآجل62',
 'باعتقادك, ما الذي جعلهم يتعاملون معك؟/اخرى63',
 'اخرى64',
 'هل يوجد منافسون لك بنفس المهنة في منطقتك',
 'هل تأثر معدل الدخل زيادة او نقصان بسبب وجود المنافسين؟',
 'كيف تقوم ببيع منتجاتك؟',
 'اشرح اجابتك بكلا الحالات',
 'اذا كان عبر تاجركيف قمت بلقائهم',
 'ما الشركات او اصحاب المشاريع التي تستخدم خدمتك / منتجاتك؟',
 'من هم عملاءك',
 'من هم عملائك',
 'هل باعتقادك ان عملائك/ زبائنك قادرين على شراء خدماتك',
 'اهم النقاط',
 'شرح اكثر',
 'كيف عرفو عنك',
 'كيف عرفو عنك/من الجوار65',
 'كيف عرفو عنك/عبر التواصل الاجتماعي66',
 'كيف عرفو عنك/من خلال صيت عملي و سمعتي67',
 'كيف عرفو عنك/بالصدفة',
 'كيف عرفو عنك/عبر الترويج و التسويق',
 'تفصيل اكثر',
 'هل تغيرت الأسعار في السوق (خلال 6/12الأشهر  الماضية) عند شراء العرض الخاص بك؟',
 'إلى أي مدى ارتفعت / انخفضت الأسعار ، هل يمكنك إعطاء النسب المئوية؟',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق.',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./ارتفاع الطلب (ارتفاع الطلب على منتج محدد قد يؤدي الى تغير سعر هذا المنتج- السلعة)70',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./انخفاض المؤونه (نفاذ كمية قد تودي الى احتكارها او عدم شراءها)',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./انخفاض الطلب( قد يؤدي الى عدم توفيرها بدوره قد يسبب البحث عن توفيره الى زياد قييمه السلعه او انخفاضها)71',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./توافر اعلى (توفر المنتج بشكل كبير قد يؤدي الى تغير في السعر اقل او اعلى)',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./إعانات من الحكومة72',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./صعوبات الوصول إلى السوق73',
 'ما هي الأسباب الرئيسية لتغير الأسعار؟ يرجى اختيار كل ما ينطبق./تدهور الوضع الامني بسبب الحروب',
 'ما مدى تكرار تعامل عميلك معك؟',
 'إذا انقطعت خدمتك أو منتجك عن المجتمع ، فكيف سيتأثر العميل أو المجتمع؟',
 'إذا انقطعت خدمتك أو منتجك عن المجتمع ، فكيف سيتأثر العميل أو المجتمع؟/أنا المزود الوحيد لهذه الخدمة76',
 'إذا انقطعت خدمتك أو منتجك عن المجتمع ، فكيف سيتأثر العميل أو المجتمع؟/ من الصعب على العميل بناء الثقة مع مورد جديد77',
 'إذا انقطعت خدمتك أو منتجك عن المجتمع ، فكيف سيتأثر العميل أو المجتمع؟/اخرى78',
 'اخرى79',
 'هل تعتقد أن المساعدة المقدمة للشركات يمكن أن تحسن عملك بحيث يمكنك بدورها استهداف المزيد من العملاء؟',
 'بخلاف الدعم الذي تلقيته ، ما الذي كنت بحاجة إلى توفيره / تقديمه / تقديمه من أجل إحداث تأثير إيجابي على تحسين  الاقتصاد في قريتك / الجوار',
 'هل يمكنك ذكر 3 اشخاص تتعامل معهم/ يتعاملون معك - قم بذكر الاسم و العنوان ورقم الهاتف اذا امكن',
 'هل يمكنك ذكر 3 اشخاص تتعامل معهم/ يتعاملون معك - قم بذكر الاسم و العنوان ورقم الهاتف اذا امكن80',
 'هل يمكنك ذكر 3 اشخاص تتعامل معهم/ يتعاملون معك - قم بذكر الاسم و العنوان ورقم الهاتف اذا امكن       ',
 '_index']

In [669]:
english_columns_list = [
    "consent_statement",
    "surveyor_name",
    "location_capture",
    "latitude",
    "longitude",
    "altitude",
    "precision",
    "survey_date",
    "governorate",
    "district_abyan",
    "district_lahj",
    "district_aldhalea",
    "village",
    "respondent_name",
    "service_craft_type",
    "business_operation_duration",
    "income_sources_option_1",
    "income_sources_option_2",
    "income_sources_option_3",
    "income_sources_option_4",
    "income_sources_option_5",
    "primary_income_source",
    "geographic_scope",
    "geographic_scope_village",
    "geographic_scope_neighborhood",
    "geographic_scope_district",
    "geographic_scope_governorate",
    "profession_choice_reason",
    "profession_choice_higher_profit",
    "profession_choice_is_my_profession",
    "profession_choice_my_expertise",
    "profession_choice_family_profession",
    "profession_choice_only_provider",
    "profession_choice_goods_scarcity",
    "profession_choice_other",
    "profession_choice_other_specify",
    "service_differentiation",
    "service_differentiation_quality",
    "service_differentiation_unique_offering",
    "service_differentiation_lower_price",
    "service_differentiation_deferred_payment",
    "service_differentiation_suitable_location",
    "service_differentiation_good_service",
    "service_differentiation_trust",
    "service_differentiation_other",
    "service_differentiation_other_specify",
    "added_new_services_after_adra",
    "new_services_explanation",
    "new_services_added_workers",
    "new_services_added_materials",
    "new_services_added_warehouse_expansion",
    "production_constraints_before_support",
    "production_constraints_before_support_explain",
    "market_price_changed_2_years",
    "market_price_change_reason",
    "price_change_reason_economic_factors",
    "price_change_reason_exchange_control",
    "price_change_reason_security_stability",
    "income_change_after_support",
    "income_change_reason_explanation",
    "business_expansion_after_income_increase",
    "expansion_type_employee_increase",
    "expansion_type_net_income_increase",
    "expansion_type_new_assets",
    "expansion_type_inventory_increase",
    "expansion_type_customer_increase",
    "expansion_type_other",
    "expansion_type_other_specify",
    "employees_count_before",
    "work_hours_per_day_before",
    "work_days_per_week_before",
    "work_months_per_year_before",
    "employees_count_after",
    "work_hours_per_day_after",
    "work_days_per_week_after",
    "work_months_per_year_after",
    "employee_source",
    "employees_from_family",
    "employees_from_outside_family",
    "employees_from_family_bool",
    "employees_from_outside_bool",
    "family_employees_count",
    "family_employees_hours_per_day",
    "family_employees_days_per_week",
    "family_employees_months_per_year",
    "outside_employees_count",
    "outside_employees_hours_per_day",
    "outside_employees_days_per_week",
    "outside_employees_months_per_year",
    "employee_payment_frequency",
    "payment_frequency_daily",
    "payment_frequency_weekly",
    "payment_frequency_monthly",
    "customer_attraction_methods",
    "column1_legacy",
    "customer_choice_reasons",
    "customer_choice_trust_in_me",
    "customer_choice_material_quality",
    "customer_choice_unique_services",
    "customer_choice_lower_price",
    "customer_choice_deferred_payment",
    "customer_choice_suitable_location",
    "customer_choice_accessibility",
    "customer_choice_other",
    "customer_choice_other_specify",
    "profit_spending_allocation",
    "profit_spending_healthcare",
    "profit_spending_business_expansion",
    "profit_spending_savings",
    "profit_spending_education",
    "profit_spending_housing",
    "profit_spending_food",
    "profit_spending_other",
    "profit_spending_other_specify",
    "market_sector_decline_reasons",
    "decline_reason_market_access",
    "decline_reason_transportation_lack",
    "decline_reason_security_absence",
    "decline_reason_market_distance",
    "decline_reason_low_prices",
    "decline_reason_transportation_costs",
    "decline_reason_other",
    "decline_reason_other_specify",
    "independent_workspace_available",
    "workspace_description",
    "workspace_other_specify",
    "product_sales_method",
    "trader_integration_with_adra_businesses",
    "purchased_from_erms_suppliers",
    "erms_purchase_purpose",
    "erms_purchase_other_specify",
    "trader_selection_reasons",
    "trader_selection_quality",
    "trader_selection_trust",
    "trader_selection_unique_products",
    "trader_selection_lower_price",
    "trader_selection_deferred_payment",
    "trader_selection_other",
    "trader_selection_other_specify",
    "trader_relationship_assessment",
    "trader_relationship_explanation",
    "traders_purchased_from_us",
    "trader_perception_of_us",
    "trader_perception_quality",
    "trader_perception_trust",
    "trader_perception_unique_offerings",
    "trader_perception_lower_price",
    "trader_perception_deferred_payment",
    "trader_perception_other",
    "trader_perception_other_specify",
    "competitors_exist_in_area",
    "competitors_income_impact",
    "product_sales_method_2",
    "sales_method_explanation",
    "trader_contact_methods",
    "business_client_companies",
    "customer_demographics",
    "customer_demographics_2",
    "customer_purchasing_ability",
    "key_points",
    "key_points_explanation",
    "customer_awareness_source",
    "awareness_source_neighborhood",
    "awareness_source_social_media",
    "awareness_source_reputation",
    "awareness_source_chance",
    "awareness_source_marketing",
    "awareness_source_detailed_explanation",
    "market_prices_changed_recent",
    "price_change_percentage",
    "price_change_reasons",
    "price_change_reason_demand_increase",
    "price_change_reason_supply_decrease",
    "price_change_reason_demand_decrease",
    "price_change_reason_supply_increase",
    "price_change_reason_government_subsidies",
    "price_change_reason_market_access",
    "price_change_reason_security_deterioration",
    "customer_transaction_frequency",
    "service_interruption_impact",
    "interruption_impact_sole_provider",
    "interruption_impact_trust_building",
    "interruption_impact_other",
    "interruption_impact_other_specify",
    "business_support_improves_outreach",
    "additional_support_needed",
    "business_contacts_name_1",
    "business_contacts_name_2",
    "business_contacts_name_3",
    "index_field"
]

print(len(erms_df.columns))
print(len(english_columns_list))

if len(erms_df.columns) != len(english_columns_list):
    print('X The number of columns in the DataFrame does not match the number of columns in the list.')
else:
    print('✓ Columns numbers match successfully! Renaming in progress...')

    # Complete translation mapping from Arabic to English following naming conventions
    complete_translation = dict(zip(erms_df.columns, english_columns_list))

    # Apply the translation
    erms_df = erms_df.rename(columns=complete_translation)

    # Display the new column names
    print("✓ Columns translated and renamed successfully!")
    print(f"\nTotal columns: {len(erms_df.columns)}")
    print("\nNew column names:")
    for i, col in enumerate(erms_df.columns, 1):
        print(f"{i}. {col}")

190
190
✓ Columns numbers match successfully! Renaming in progress...
✓ Columns translated and renamed successfully!

Total columns: 190

New column names:
1. consent_statement
2. surveyor_name
3. location_capture
4. latitude
5. longitude
6. altitude
7. precision
8. survey_date
9. governorate
10. district_abyan
11. district_lahj
12. district_aldhalea
13. village
14. respondent_name
15. service_craft_type
16. business_operation_duration
17. income_sources_option_1
18. income_sources_option_2
19. income_sources_option_3
20. income_sources_option_4
21. income_sources_option_5
22. primary_income_source
23. geographic_scope
24. geographic_scope_village
25. geographic_scope_neighborhood
26. geographic_scope_district
27. geographic_scope_governorate
28. profession_choice_reason
29. profession_choice_higher_profit
30. profession_choice_is_my_profession
31. profession_choice_my_expertise
32. profession_choice_family_profession
33. profession_choice_only_provider
34. profession_choice_goods_scarcity
35. profession_choice_other
36. profession_choice_other_specify
37. service_differentiation
38. service_differentiation_quality
39. service_differentiation_unique_offering
40. service_differentiation_lower_price
41. service_differentiation_deferred_payment
42. service_differentiation_suitable_location
43. service_differentiation_good_service
44. service_differentiation_trust
45. service_differentiation_other
46. service_differentiation_other_specify
47. added_new_services_after_adra
48. new_services_explanation
49. new_services_added_workers
50. new_services_added_materials
51. new_services_added_warehouse_expansion
52. production_constraints_before_support
53. production_constraints_before_support_explain
54. market_price_changed_2_years
55. market_price_change_reason
56. price_change_reason_economic_factors
57. price_change_reason_exchange_control
58. price_change_reason_security_stability
59. income_change_after_support
60. income_change_reason_explanation
61. business_expansion_after_income_increase
62. expansion_type_employee_increase
63. expansion_type_net_income_increase
64. expansion_type_new_assets
65. expansion_type_inventory_increase
66. expansion_type_customer_increase
67. expansion_type_other
68. expansion_type_other_specify
69. employees_count_before
70. work_hours_per_day_before
71. work_days_per_week_before
72. work_months_per_year_before
73. employees_count_after
74. work_hours_per_day_after
75. work_days_per_week_after
76. work_months_per_year_after
77. employee_source
78. employees_from_family
79. employees_from_outside_family
80. employees_from_family_bool
81. employees_from_outside_bool
82. family_employees_count
83. family_employees_hours_per_day
84. family_employees_days_per_week
85. family_employees_months_per_year
86. outside_employees_count
87. outside_employees_hours_per_day
88. outside_employees_days_per_week
89. outside_employees_months_per_year
90. employee_payment_frequency
91. payment_frequency_daily
92. payment_frequency_weekly
93. payment_frequency_monthly
94. customer_attraction_methods
95. column1_legacy
96. customer_choice_reasons
97. customer_choice_trust_in_me
98. customer_choice_material_quality
99. customer_choice_unique_services
100. customer_choice_lower_price
101. customer_choice_deferred_payment
102. customer_choice_suitable_location
103. customer_choice_accessibility
104. customer_choice_other
105. customer_choice_other_specify
106. profit_spending_allocation
107. profit_spending_healthcare
108. profit_spending_business_expansion
109. profit_spending_savings
110. profit_spending_education
111. profit_spending_housing
112. profit_spending_food
113. profit_spending_other
114. profit_spending_other_specify
115. market_sector_decline_reasons
116. decline_reason_market_access
117. decline_reason_transportation_lack
118. decline_reason_security_absence
119. decline_reason_market_distance
120. decline_reason_low_prices
121. decline_reason_transportation_costs
122. decline_reason_other
123. decline_reason_other_specify
124. independent_workspace_available
125. workspace_description
126. workspace_other_specify
127. product_sales_method
128. trader_integration_with_adra_businesses
129. purchased_from_erms_suppliers
130. erms_purchase_purpose
131. erms_purchase_other_specify
132. trader_selection_reasons
133. trader_selection_quality
134. trader_selection_trust
135. trader_selection_unique_products
136. trader_selection_lower_price
137. trader_selection_deferred_payment
138. trader_selection_other
139. trader_selection_other_specify
140. trader_relationship_assessment
141. trader_relationship_explanation
142. traders_purchased_from_us
143. trader_perception_of_us
144. trader_perception_quality
145. trader_perception_trust
146. trader_perception_unique_offerings
147. trader_perception_lower_price
148. trader_perception_deferred_payment
149. trader_perception_other
150. trader_perception_other_specify
151. competitors_exist_in_area
152. competitors_income_impact
153. product_sales_method_2
154. sales_method_explanation
155. trader_contact_methods
156. business_client_companies
157. customer_demographics
158. customer_demographics_2
159. customer_purchasing_ability
160. key_points
161. key_points_explanation
162. customer_awareness_source
163. awareness_source_neighborhood
164. awareness_source_social_media
165. awareness_source_reputation
166. awareness_source_chance
167. awareness_source_marketing
168. awareness_source_detailed_explanation
169. market_prices_changed_recent
170. price_change_percentage
171. price_change_reasons
172. price_change_reason_demand_increase
173. price_change_reason_supply_decrease
174. price_change_reason_demand_decrease
175. price_change_reason_supply_increase
176. price_change_reason_government_subsidies
177. price_change_reason_market_access
178. price_change_reason_security_deterioration
179. customer_transaction_frequency
180. service_interruption_impact
181. interruption_impact_sole_provider
182. interruption_impact_trust_building
183. interruption_impact_other
184. interruption_impact_other_specify
185. business_support_improves_outreach
186. additional_support_needed
187. business_contacts_name_1
188. business_contacts_name_2
189. business_contacts_name_3
190. index_field

In [670]:
columns_to_drop_indices = [0, 1, 2, 16, 22, 27, 36, 45, 47, 
                        51, 51, 54, 60, 89, 93, 94, 95, 104,
                        105, 114, 122, 125, 129, 131, 138,
                        140, 142, 149, 153, 154, 157, 160,
                        161, 167, 170, 179, 183, 184, 185,
                        186, 187, 188, 189]
# --- Two-Step Drop Process ---

# Get the actual column names (labels) corresponding to these positions
# Use the .columns attribute and index it with the list of positions
column_names_to_drop = erms_df.columns[columns_to_drop_indices].tolist()

# Execute the drop operation using the column NAMES
# inplace=True modifies the erms_df directly
print(f"Original shape of erms_df: {erms_df.shape}")

erms_df.drop(columns=column_names_to_drop, inplace=True)

print(f"New shape of erms_df: {erms_df.shape}")
print(f"Columns dropped: {len(column_names_to_drop)}")

Original shape of erms_df: (320, 190)
New shape of erms_df: (320, 148)
Columns dropped: 43

In [671]:
with pd.option_context('display.max_columns', None):
    display(erms_df.sample(3))

,latitude,longitude,altitude,precision,survey_date,governorate,district_abyan,district_lahj,district_aldhalea,village,respondent_name,service_craft_type,business_operation_duration,income_sources_option_2,income_sources_option_3,income_sources_option_4,income_sources_option_5,primary_income_source,geographic_scope_village,geographic_scope_neighborhood,geographic_scope_district,geographic_scope_governorate,profession_choice_higher_profit,profession_choice_is_my_profession,profession_choice_my_expertise,profession_choice_family_profession,profession_choice_only_provider,profession_choice_goods_scarcity,profession_choice_other,profession_choice_other_specify,service_differentiation_quality,service_differentiation_unique_offering,service_differentiation_lower_price,service_differentiation_deferred_payment,service_differentiation_suitable_location,service_differentiation_good_service,service_differentiation_trust,service_differentiation_other,added_new_services_after_adra,new_services_added_workers,new_services_added_materials,new_services_added_warehouse_expansion,production_constraints_before_support_explain,market_price_changed_2_years,price_change_reason_economic_factors,price_change_reason_exchange_control,price_change_reason_security_stability,income_change_after_support,income_change_reason_explanation,expansion_type_employee_increase,expansion_type_net_income_increase,expansion_type_new_assets,expansion_type_inventory_increase,expansion_type_customer_increase,expansion_type_other,expansion_type_other_specify,employees_count_before,work_hours_per_day_before,work_days_per_week_before,work_months_per_year_before,employees_count_after,work_hours_per_day_after,work_days_per_week_after,work_months_per_year_after,employee_source,employees_from_family,employees_from_outside_family,employees_from_family_bool,employees_from_outside_bool,family_employees_count,family_employees_hours_per_day,family_employees_days_per_week,family_employees_months_per_year,outside_employees_count,outside_employees_hours_per_day,outside_employees_days_per_week,outside_employees_months_per_year,payment_frequency_daily,payment_frequency_weekly,payment_frequency_monthly,customer_choice_trust_in_me,customer_choice_material_quality,customer_choice_unique_services,customer_choice_lower_price,customer_choice_deferred_payment,customer_choice_suitable_location,customer_choice_accessibility,customer_choice_other,profit_spending_healthcare,profit_spending_business_expansion,profit_spending_savings,profit_spending_education,profit_spending_housing,profit_spending_food,profit_spending_other,profit_spending_other_specify,decline_reason_market_access,decline_reason_transportation_lack,decline_reason_security_absence,decline_reason_market_distance,decline_reason_low_prices,decline_reason_transportation_costs,decline_reason_other,independent_workspace_available,workspace_description,product_sales_method,trader_integration_with_adra_businesses,purchased_from_erms_suppliers,erms_purchase_other_specify,trader_selection_quality,trader_selection_trust,trader_selection_unique_products,trader_selection_lower_price,trader_selection_deferred_payment,trader_selection_other,trader_relationship_assessment,traders_purchased_from_us,trader_perception_quality,trader_perception_trust,trader_perception_unique_offerings,trader_perception_lower_price,trader_perception_deferred_payment,trader_perception_other,competitors_exist_in_area,competitors_income_impact,product_sales_method_2,business_client_companies,customer_demographics,customer_purchasing_ability,key_points,awareness_source_neighborhood,awareness_source_social_media,awareness_source_reputation,awareness_source_chance,awareness_source_marketing,market_prices_changed_recent,price_change_percentage,price_change_reason_demand_increase,price_change_reason_supply_decrease,price_change_reason_demand_decrease,price_change_reason_supply_increase,price_change_reason_government_subsidies,price_change_reason_market_access,price_change_reason_security_deterioration,customer_transaction_frequency,interruption_impact_sole_provider,interruption_impact_trust_building,interruption_impact_other
206,13.294476,45.295566,104.849060,4.698,2020-12-13,Abyan,Khanfir,NaN,NaN,الحصن,فاطمة حيدرة دخشوشة 736376174,صناعة وبيع البخور والعطور,4,NaN,NaN,NaN,1,دخل البخور,1,1,0,0,1,1,1,1,0,0,0,NaN,1,0,1,1,0,1,0,0,نعم,0.0,1.0,0.0,NaN,نعم,1,1.0,0.0,في زيادة,بسبب الدعم وتنوع المواد يعني أني ضفت حاجات أخرى غير البخور مثل الزباد والآخضرين وغيرها من الأشياء وذالك سبب في زيادة الدخل,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,لا,NaN,كلاهما,OK,لا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,نقصان,تجزئة,لا يوجد فقط افراد,افراد,نعم,بتوفير الدفع النقد و الاجل,1,0,1,0,0.0,زادت,0.5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,بشكل شهري,0,1,0
52,13.231299,45.305774,58.391479,6.603,2020-12-07,Abyan,Khanfir,NaN,NaN,جعار - حافة قدر الله,جمعة عبدالله هادي,دلالة وبيع الملابس,4,NaN,NaN,NaN,1,دلالة و بيع الملابس,1,1,1,0,1,1,1,0,0,0,0,NaN,1,0,1,1,0,1,1,0,نعم,0.0,1.0,0.0,NaN,نعم,1,1.0,0.0,في زيادة,سبب الزيادة يكمن في ارتفاع ارباح الفوائد,0.0,1.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,0,1,1,0,0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,غرفة,دين,OK,لا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,زيادة,تجزئة,لا يوجد فقط افراد,افراد,نعم,بتوفير الدفع النقد و الاجل,1,0,1,0,1.0,زادت,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,بشكل دائم,0,1,1
277,13.137082,45.364629,16.588135,4.912,2020-12-15,Abyan,Zingibar,NaN,NaN,زنجبار _عمودية,سالمه عبيد يحيى 737160405 رقم الزوج,خياطة,4,اشتغل بمدرسة براتب 10 الف بالشهر,NaN,NaN,2,دخل الخياطة,1,1,0,0,1,1,1,1,0,0,0,NaN,0,1,1,1,0,0,1,0,نعم,0.0,1.0,0.0,NaN,نعم,1,1.0,0.0,في زيادة,بسبب زيادة الشغل وايضا توسعت ورجعت ابيع بعض اشياء للاطفال من داخل البيت,0.0,0.0,1.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,لا,NaN,كلاهما,OK,نعم,NaN,1.0,1.0,0.0,1.0,1.0,0.0,جيد جدا,نعم,0.0,1.0,1.0,1.0,1.0,0.0,نعم,زيادة,تجزئة,لا يوجد فقط افراد,افراد,نعم,بتوفير الدفع النقد و الاجل,1,0,1,0,0.0,زادت,0.5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,بشكل شهري,0,1,0

In [672]:
erms_df['survey_date'] = pd.to_datetime(erms_df['survey_date'])
erms_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 148 columns):
 #    Column                                         Non-Null Count  Dtype
---   ------                                         --------------  -----
 0    latitude                                       295 non-null    float64
 1    longitude                                      295 non-null    float64
 2    altitude                                       295 non-null    float64
 3    precision                                      295 non-null    float64
 4    survey_date                                    320 non-null    datetime64[ns]
 5    governorate                                    320 non-null    object
 6    district_abyan                                 226 non-null    object
 7    district_lahj                                  69 non-null     object
 8    district_aldhalea                              25 non-null     object
 9    village                                        320 non-null    object
 10   respondent_name                                320 non-null    object
 11   service_craft_type                             320 non-null    object
 12   business_operation_duration                    320 non-null    int64
 13   income_sources_option_2                        110 non-null    object
 14   income_sources_option_3                        23 non-null     object
 15   income_sources_option_4                        4 non-null      object
 16   income_sources_option_5                        320 non-null    int64
 17   primary_income_source                          320 non-null    object
 18   geographic_scope_village                       320 non-null    int64
 19   geographic_scope_neighborhood                  320 non-null    int64
 20   geographic_scope_district                      320 non-null    int64
 21   geographic_scope_governorate                   320 non-null    int64
 22   profession_choice_higher_profit                320 non-null    int64
 23   profession_choice_is_my_profession             320 non-null    int64
 24   profession_choice_my_expertise                 320 non-null    int64
 25   profession_choice_family_profession            320 non-null    int64
 26   profession_choice_only_provider                320 non-null    int64
 27   profession_choice_goods_scarcity               320 non-null    int64
 28   profession_choice_other                        320 non-null    int64
 29   profession_choice_other_specify                6 non-null      object
 30   service_differentiation_quality                320 non-null    int64
 31   service_differentiation_unique_offering        320 non-null    int64
 32   service_differentiation_lower_price            320 non-null    int64
 33   service_differentiation_deferred_payment       320 non-null    int64
 34   service_differentiation_suitable_location      320 non-null    int64
 35   service_differentiation_good_service           320 non-null    int64
 36   service_differentiation_trust                  320 non-null    int64
 37   service_differentiation_other                  320 non-null    int64
 38   added_new_services_after_adra                  320 non-null    object
 39   new_services_added_workers                     292 non-null    float64
 40   new_services_added_materials                   292 non-null    float64
 41   new_services_added_warehouse_expansion         292 non-null    float64
 42   production_constraints_before_support_explain  28 non-null     object
 43   market_price_changed_2_years                   320 non-null    object
 44   price_change_reason_economic_factors           320 non-null    int64
 45   price_change_reason_exchange_control           319 non-null    float64
 46   price_change_reason_security_stability         319 non-null    float64
 47   income_change_after_support                    320 non-null    object
 48   income_change_reason_explanation               320 non-null    object
 49   expansion_type_employee_increase               198 non-null    float64
 50   expansion_type_net_income_increase             198 non-null    float64
 51   expansion_type_new_assets                      198 non-null    float64
 52   expansion_type_inventory_increase              198 non-null    float64
 53   expansion_type_customer_increase               198 non-null    float64
 54   expansion_type_other                           198 non-null    float64
 55   expansion_type_other_specify                   1 non-null      object
 56   employees_count_before                         49 non-null     float64
 57   work_hours_per_day_before                      49 non-null     float64
 58   work_days_per_week_before                      49 non-null     float64
 59   work_months_per_year_before                    49 non-null     float64
 60   employees_count_after                          49 non-null     float64
 61   work_hours_per_day_after                       49 non-null     float64
 62   work_days_per_week_after                       49 non-null     float64
 63   work_months_per_year_after                     49 non-null     float64
 64   employee_source                                49 non-null     object
 65   employees_from_family                          47 non-null     float64
 66   employees_from_outside_family                  47 non-null     float64
 67   employees_from_family_bool                     49 non-null     float64
 68   employees_from_outside_bool                    49 non-null     float64
 69   family_employees_count                         39 non-null     float64
 70   family_employees_hours_per_day                 39 non-null     float64
 71   family_employees_days_per_week                 39 non-null     float64
 72   family_employees_months_per_year               39 non-null     float64
 73   outside_employees_count                        19 non-null     float64
 74   outside_employees_hours_per_day                19 non-null     float64
 75   outside_employees_days_per_week                19 non-null     float64
 76   outside_employees_months_per_year              19 non-null     float64
 77   payment_frequency_daily                        49 non-null     float64
 78   payment_frequency_weekly                       49 non-null     float64
 79   payment_frequency_monthly                      49 non-null     float64
 80   customer_choice_trust_in_me                    320 non-null    int64
 81   customer_choice_material_quality               320 non-null    int64
 82   customer_choice_unique_services                320 non-null    int64
 83   customer_choice_lower_price                    320 non-null    int64
 84   customer_choice_deferred_payment               320 non-null    int64
 85   customer_choice_suitable_location              320 non-null    int64
 86   customer_choice_accessibility                  320 non-null    int64
 87   customer_choice_other                          320 non-null    int64
 88   profit_spending_healthcare                     115 non-null    float64
 89   profit_spending_business_expansion             115 non-null    float64
 90   profit_spending_savings                        115 non-null    float64
 91   profit_spending_education                      115 non-null    float64
 92   profit_spending_housing                        115 non-null    float64
 93   profit_spending_food                           115 non-null    float64
 94   profit_spending_other                          114 non-null    float64
 95   profit_spending_other_specify                  0 non-null      float64
 96   decline_reason_market_access                   122 non-null    float64
 97   decline_reason_transportation_lack             122 non-null    float64
 98   decline_reason_security_absence                122 non-null    float64
 99   decline_reason_market_distance                 122 non-null    float64
 100  decline_reason_low_prices                      122 non-null    float64
 101  decline_reason_transportation_costs            122 non-null    float64
 102  decline_reason_other                           122 non-null    float64
 103  independent_workspace_available                320 non-null    object
 104  workspace_description                          199 non-null    object
 105  product_sales_method                           320 non-null    object
 106  trader_integration_with_adra_businesses        233 non-null    object
 107  purchased_from_erms_suppliers                  320 non-null    object
 108  erms_purchase_other_specify                    21 non-null     object
 109  trader_selection_quality                       107 non-null    float64
 110  trader_selection_trust                         107 non-null    float64
 111  trader_selection_unique_products               107 non-null    float64
 112  trader_selection_lower_price                   107 non-null    float64
 113  trader_selection_deferred_payment              107 non-null    float64
 114  trader_selection_other                         107 non-null    float64
 115  trader_relationship_assessment                 107 non-null    object
 116  traders_purchased_from_us                      107 non-null    object
 117  trader_perception_quality                      93 non-null     float64
 118  trader_perception_trust                        93 non-null     float64
 119  trader_perception_unique_offerings             93 non-null     float64
 120  trader_perception_lower_price                  93 non-null     float64
 121  trader_perception_deferred_payment             93 non-null     float64
 122  trader_perception_other                        93 non-null     float64
 123  competitors_exist_in_area                      320 non-null    object
 124  competitors_income_impact                      274 non-null    object
 125  product_sales_method_2                         320 non-null    object
 126  business_client_companies                      320 non-null    object
 127  customer_demographics                          320 non-null    object
 128  customer_purchasing_ability                    320 non-null    object
 129  key_points                                     320 non-null    object
 130  awareness_source_neighborhood                  320 non-null    int64
 131  awareness_source_social_media                  320 non-null    int64
 132  awareness_source_reputation                    320 non-null    int64
 133  awareness_source_chance                        320 non-null    int64
 134  awareness_source_marketing                     306 non-null    float64
 135  market_prices_changed_recent                   320 non-null    object
 136  price_change_percentage                        318 non-null    float64
 137  price_change_reason_demand_increase            317 non-null    float64
 138  price_change_reason_supply_decrease            317 non-null    float64
 139  price_change_reason_demand_decrease            317 non-null    float64
 140  price_change_reason_supply_increase            317 non-null    float64
 141  price_change_reason_government_subsidies       317 non-null    float64
 142  price_change_reason_market_access              317 non-null    float64
 143  price_change_reason_security_deterioration     317 non-null    float64
 144  customer_transaction_frequency                 320 non-null    object
 145  interruption_impact_sole_provider              320 non-null    int64
 146  interruption_impact_trust_building             320 non-null    int64
 147  interruption_impact_other                      320 non-null    int64
dtypes: datetime64[ns](1), float64(74), int64(37), object(36)
memory usage: 370.1+ KB

In [673]:
# This overrides the default maximum of 100 columns for info() output.
pd.set_option('display.max_info_columns', 200) 

erms_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 148 columns):
 #    Column                                         Non-Null Count  Dtype
---   ------                                         --------------  -----
 0    latitude                                       295 non-null    float64
 1    longitude                                      295 non-null    float64
 2    altitude                                       295 non-null    float64
 3    precision                                      295 non-null    float64
 4    survey_date                                    320 non-null    datetime64[ns]
 5    governorate                                    320 non-null    object
 6    district_abyan                                 226 non-null    object
 7    district_lahj                                  69 non-null     object
 8    district_aldhalea                              25 non-null     object
 9    village                                        320 non-null    object
 10   respondent_name                                320 non-null    object
 11   service_craft_type                             320 non-null    object
 12   business_operation_duration                    320 non-null    int64
 13   income_sources_option_2                        110 non-null    object
 14   income_sources_option_3                        23 non-null     object
 15   income_sources_option_4                        4 non-null      object
 16   income_sources_option_5                        320 non-null    int64
 17   primary_income_source                          320 non-null    object
 18   geographic_scope_village                       320 non-null    int64
 19   geographic_scope_neighborhood                  320 non-null    int64
 20   geographic_scope_district                      320 non-null    int64
 21   geographic_scope_governorate                   320 non-null    int64
 22   profession_choice_higher_profit                320 non-null    int64
 23   profession_choice_is_my_profession             320 non-null    int64
 24   profession_choice_my_expertise                 320 non-null    int64
 25   profession_choice_family_profession            320 non-null    int64
 26   profession_choice_only_provider                320 non-null    int64
 27   profession_choice_goods_scarcity               320 non-null    int64
 28   profession_choice_other                        320 non-null    int64
 29   profession_choice_other_specify                6 non-null      object
 30   service_differentiation_quality                320 non-null    int64
 31   service_differentiation_unique_offering        320 non-null    int64
 32   service_differentiation_lower_price            320 non-null    int64
 33   service_differentiation_deferred_payment       320 non-null    int64
 34   service_differentiation_suitable_location      320 non-null    int64
 35   service_differentiation_good_service           320 non-null    int64
 36   service_differentiation_trust                  320 non-null    int64
 37   service_differentiation_other                  320 non-null    int64
 38   added_new_services_after_adra                  320 non-null    object
 39   new_services_added_workers                     292 non-null    float64
 40   new_services_added_materials                   292 non-null    float64
 41   new_services_added_warehouse_expansion         292 non-null    float64
 42   production_constraints_before_support_explain  28 non-null     object
 43   market_price_changed_2_years                   320 non-null    object
 44   price_change_reason_economic_factors           320 non-null    int64
 45   price_change_reason_exchange_control           319 non-null    float64
 46   price_change_reason_security_stability         319 non-null    float64
 47   income_change_after_support                    320 non-null    object
 48   income_change_reason_explanation               320 non-null    object
 49   expansion_type_employee_increase               198 non-null    float64
 50   expansion_type_net_income_increase             198 non-null    float64
 51   expansion_type_new_assets                      198 non-null    float64
 52   expansion_type_inventory_increase              198 non-null    float64
 53   expansion_type_customer_increase               198 non-null    float64
 54   expansion_type_other                           198 non-null    float64
 55   expansion_type_other_specify                   1 non-null      object
 56   employees_count_before                         49 non-null     float64
 57   work_hours_per_day_before                      49 non-null     float64
 58   work_days_per_week_before                      49 non-null     float64
 59   work_months_per_year_before                    49 non-null     float64
 60   employees_count_after                          49 non-null     float64
 61   work_hours_per_day_after                       49 non-null     float64
 62   work_days_per_week_after                       49 non-null     float64
 63   work_months_per_year_after                     49 non-null     float64
 64   employee_source                                49 non-null     object
 65   employees_from_family                          47 non-null     float64
 66   employees_from_outside_family                  47 non-null     float64
 67   employees_from_family_bool                     49 non-null     float64
 68   employees_from_outside_bool                    49 non-null     float64
 69   family_employees_count                         39 non-null     float64
 70   family_employees_hours_per_day                 39 non-null     float64
 71   family_employees_days_per_week                 39 non-null     float64
 72   family_employees_months_per_year               39 non-null     float64
 73   outside_employees_count                        19 non-null     float64
 74   outside_employees_hours_per_day                19 non-null     float64
 75   outside_employees_days_per_week                19 non-null     float64
 76   outside_employees_months_per_year              19 non-null     float64
 77   payment_frequency_daily                        49 non-null     float64
 78   payment_frequency_weekly                       49 non-null     float64
 79   payment_frequency_monthly                      49 non-null     float64
 80   customer_choice_trust_in_me                    320 non-null    int64
 81   customer_choice_material_quality               320 non-null    int64
 82   customer_choice_unique_services                320 non-null    int64
 83   customer_choice_lower_price                    320 non-null    int64
 84   customer_choice_deferred_payment               320 non-null    int64
 85   customer_choice_suitable_location              320 non-null    int64
 86   customer_choice_accessibility                  320 non-null    int64
 87   customer_choice_other                          320 non-null    int64
 88   profit_spending_healthcare                     115 non-null    float64
 89   profit_spending_business_expansion             115 non-null    float64
 90   profit_spending_savings                        115 non-null    float64
 91   profit_spending_education                      115 non-null    float64
 92   profit_spending_housing                        115 non-null    float64
 93   profit_spending_food                           115 non-null    float64
 94   profit_spending_other                          114 non-null    float64
 95   profit_spending_other_specify                  0 non-null      float64
 96   decline_reason_market_access                   122 non-null    float64
 97   decline_reason_transportation_lack             122 non-null    float64
 98   decline_reason_security_absence                122 non-null    float64
 99   decline_reason_market_distance                 122 non-null    float64
 100  decline_reason_low_prices                      122 non-null    float64
 101  decline_reason_transportation_costs            122 non-null    float64
 102  decline_reason_other                           122 non-null    float64
 103  independent_workspace_available                320 non-null    object
 104  workspace_description                          199 non-null    object
 105  product_sales_method                           320 non-null    object
 106  trader_integration_with_adra_businesses        233 non-null    object
 107  purchased_from_erms_suppliers                  320 non-null    object
 108  erms_purchase_other_specify                    21 non-null     object
 109  trader_selection_quality                       107 non-null    float64
 110  trader_selection_trust                         107 non-null    float64
 111  trader_selection_unique_products               107 non-null    float64
 112  trader_selection_lower_price                   107 non-null    float64
 113  trader_selection_deferred_payment              107 non-null    float64
 114  trader_selection_other                         107 non-null    float64
 115  trader_relationship_assessment                 107 non-null    object
 116  traders_purchased_from_us                      107 non-null    object
 117  trader_perception_quality                      93 non-null     float64
 118  trader_perception_trust                        93 non-null     float64
 119  trader_perception_unique_offerings             93 non-null     float64
 120  trader_perception_lower_price                  93 non-null     float64
 121  trader_perception_deferred_payment             93 non-null     float64
 122  trader_perception_other                        93 non-null     float64
 123  competitors_exist_in_area                      320 non-null    object
 124  competitors_income_impact                      274 non-null    object
 125  product_sales_method_2                         320 non-null    object
 126  business_client_companies                      320 non-null    object
 127  customer_demographics                          320 non-null    object
 128  customer_purchasing_ability                    320 non-null    object
 129  key_points                                     320 non-null    object
 130  awareness_source_neighborhood                  320 non-null    int64
 131  awareness_source_social_media                  320 non-null    int64
 132  awareness_source_reputation                    320 non-null    int64
 133  awareness_source_chance                        320 non-null    int64
 134  awareness_source_marketing                     306 non-null    float64
 135  market_prices_changed_recent                   320 non-null    object
 136  price_change_percentage                        318 non-null    float64
 137  price_change_reason_demand_increase            317 non-null    float64
 138  price_change_reason_supply_decrease            317 non-null    float64
 139  price_change_reason_demand_decrease            317 non-null    float64
 140  price_change_reason_supply_increase            317 non-null    float64
 141  price_change_reason_government_subsidies       317 non-null    float64
 142  price_change_reason_market_access              317 non-null    float64
 143  price_change_reason_security_deterioration     317 non-null    float64
 144  customer_transaction_frequency                 320 non-null    object
 145  interruption_impact_sole_provider              320 non-null    int64
 146  interruption_impact_trust_building             320 non-null    int64
 147  interruption_impact_other                      320 non-null    int64
dtypes: datetime64[ns](1), float64(74), int64(37), object(36)
memory usage: 370.1+ KB

In [674]:
# Create mapping from respondent_name to respondent_id
unique_respondents = erms_df['respondent_name'].unique()

# Create sequential IDs in format R001, R002, etc.
respondent_mapping = {
    name: f"R{str(i+1).zfill(3)}" 
    for i, name in enumerate(unique_respondents)
}

# Create respondent_id column
erms_df['respondent_id'] = erms_df['respondent_name'].map(respondent_mapping)

# Drop the original respondent_name column
erms_df = erms_df.drop('respondent_name', axis=1)

# Reorder columns to put respondent_id after location data
cols = erms_df.columns.tolist()
cols.remove('respondent_id')

# Find position after 'village' (or adjust as needed)
if 'village' in cols:
    village_idx = cols.index('village')
    cols.insert(village_idx + 1, 'respondent_id')
else:
    # Put at beginning if village not found
    cols = ['respondent_id'] + cols

erms_df = erms_df[cols]

print(f"✓ Created {len(unique_respondents)} respondent IDs")
print(f"  Format: R001 to R{str(len(unique_respondents)).zfill(3)}")
print(f"\nFirst 5 mappings:")

✓ Created 320 respondent IDs
  Format: R001 to R320

First 5 mappings:

In [675]:
# Save mapping to a separate confidential file

mapping_df = pd.DataFrame(
    list(respondent_mapping.items()), 
    columns=['respondent_name', 'respondent_id']
)
mapping_df.to_csv('erms_respondent_mapping_CONFIDENTIAL.csv', index=False)
print("\n⚠️  Mapping saved to: erms_respondent_mapping_CONFIDENTIAL.csv")
print("    (Keep this file secure - contains PII)")

⚠️  Mapping saved to: erms_respondent_mapping_CONFIDENTIAL.csv
    (Keep this file secure - contains PII)

In [676]:
erms_df.columns.tolist()

['latitude',
 'longitude',
 'altitude',
 'precision',
 'survey_date',
 'governorate',
 'district_abyan',
 'district_lahj',
 'district_aldhalea',
 'village',
 'respondent_id',
 'service_craft_type',
 'business_operation_duration',
 'income_sources_option_2',
 'income_sources_option_3',
 'income_sources_option_4',
 'income_sources_option_5',
 'primary_income_source',
 'geographic_scope_village',
 'geographic_scope_neighborhood',
 'geographic_scope_district',
 'geographic_scope_governorate',
 'profession_choice_higher_profit',
 'profession_choice_is_my_profession',
 'profession_choice_my_expertise',
 'profession_choice_family_profession',
 'profession_choice_only_provider',
 'profession_choice_goods_scarcity',
 'profession_choice_other',
 'profession_choice_other_specify',
 'service_differentiation_quality',
 'service_differentiation_unique_offering',
 'service_differentiation_lower_price',
 'service_differentiation_deferred_payment',
 'service_differentiation_suitable_location',
 'service_differentiation_good_service',
 'service_differentiation_trust',
 'service_differentiation_other',
 'added_new_services_after_adra',
 'new_services_added_workers',
 'new_services_added_materials',
 'new_services_added_warehouse_expansion',
 'production_constraints_before_support_explain',
 'market_price_changed_2_years',
 'price_change_reason_economic_factors',
 'price_change_reason_exchange_control',
 'price_change_reason_security_stability',
 'income_change_after_support',
 'income_change_reason_explanation',
 'expansion_type_employee_increase',
 'expansion_type_net_income_increase',
 'expansion_type_new_assets',
 'expansion_type_inventory_increase',
 'expansion_type_customer_increase',
 'expansion_type_other',
 'expansion_type_other_specify',
 'employees_count_before',
 'work_hours_per_day_before',
 'work_days_per_week_before',
 'work_months_per_year_before',
 'employees_count_after',
 'work_hours_per_day_after',
 'work_days_per_week_after',
 'work_months_per_year_after',
 'employee_source',
 'employees_from_family',
 'employees_from_outside_family',
 'employees_from_family_bool',
 'employees_from_outside_bool',
 'family_employees_count',
 'family_employees_hours_per_day',
 'family_employees_days_per_week',
 'family_employees_months_per_year',
 'outside_employees_count',
 'outside_employees_hours_per_day',
 'outside_employees_days_per_week',
 'outside_employees_months_per_year',
 'payment_frequency_daily',
 'payment_frequency_weekly',
 'payment_frequency_monthly',
 'customer_choice_trust_in_me',
 'customer_choice_material_quality',
 'customer_choice_unique_services',
 'customer_choice_lower_price',
 'customer_choice_deferred_payment',
 'customer_choice_suitable_location',
 'customer_choice_accessibility',
 'customer_choice_other',
 'profit_spending_healthcare',
 'profit_spending_business_expansion',
 'profit_spending_savings',
 'profit_spending_education',
 'profit_spending_housing',
 'profit_spending_food',
 'profit_spending_other',
 'profit_spending_other_specify',
 'decline_reason_market_access',
 'decline_reason_transportation_lack',
 'decline_reason_security_absence',
 'decline_reason_market_distance',
 'decline_reason_low_prices',
 'decline_reason_transportation_costs',
 'decline_reason_other',
 'independent_workspace_available',
 'workspace_description',
 'product_sales_method',
 'trader_integration_with_adra_businesses',
 'purchased_from_erms_suppliers',
 'erms_purchase_other_specify',
 'trader_selection_quality',
 'trader_selection_trust',
 'trader_selection_unique_products',
 'trader_selection_lower_price',
 'trader_selection_deferred_payment',
 'trader_selection_other',
 'trader_relationship_assessment',
 'traders_purchased_from_us',
 'trader_perception_quality',
 'trader_perception_trust',
 'trader_perception_unique_offerings',
 'trader_perception_lower_price',
 'trader_perception_deferred_payment',
 'trader_perception_other',
 'competitors_exist_in_area',
 'competitors_income_impact',
 'product_sales_method_2',
 'business_client_companies',
 'customer_demographics',
 'customer_purchasing_ability',
 'key_points',
 'awareness_source_neighborhood',
 'awareness_source_social_media',
 'awareness_source_reputation',
 'awareness_source_chance',
 'awareness_source_marketing',
 'market_prices_changed_recent',
 'price_change_percentage',
 'price_change_reason_demand_increase',
 'price_change_reason_supply_decrease',
 'price_change_reason_demand_decrease',
 'price_change_reason_supply_increase',
 'price_change_reason_government_subsidies',
 'price_change_reason_market_access',
 'price_change_reason_security_deterioration',
 'customer_transaction_frequency',
 'interruption_impact_sole_provider',
 'interruption_impact_trust_building',
 'interruption_impact_other']

In [677]:
erms_df['district_abyan'] = erms_df['district_abyan'].fillna(erms_df['district_aldhalea'].fillna(erms_df['district_lahj']))

# drop the columns district_abyan, district_aldalea, district_lahj
erms_df = erms_df.drop(columns=['district_aldhalea', 'district_lahj'])

# rename the column district_abyan to district
erms_df = erms_df.rename(columns={'district_abyan': 'district'})

erms_df.columns.to_list()

['latitude',
 'longitude',
 'altitude',
 'precision',
 'survey_date',
 'governorate',
 'district',
 'village',
 'respondent_id',
 'service_craft_type',
 'business_operation_duration',
 'income_sources_option_2',
 'income_sources_option_3',
 'income_sources_option_4',
 'income_sources_option_5',
 'primary_income_source',
 'geographic_scope_village',
 'geographic_scope_neighborhood',
 'geographic_scope_district',
 'geographic_scope_governorate',
 'profession_choice_higher_profit',
 'profession_choice_is_my_profession',
 'profession_choice_my_expertise',
 'profession_choice_family_profession',
 'profession_choice_only_provider',
 'profession_choice_goods_scarcity',
 'profession_choice_other',
 'profession_choice_other_specify',
 'service_differentiation_quality',
 'service_differentiation_unique_offering',
 'service_differentiation_lower_price',
 'service_differentiation_deferred_payment',
 'service_differentiation_suitable_location',
 'service_differentiation_good_service',
 'service_differentiation_trust',
 'service_differentiation_other',
 'added_new_services_after_adra',
 'new_services_added_workers',
 'new_services_added_materials',
 'new_services_added_warehouse_expansion',
 'production_constraints_before_support_explain',
 'market_price_changed_2_years',
 'price_change_reason_economic_factors',
 'price_change_reason_exchange_control',
 'price_change_reason_security_stability',
 'income_change_after_support',
 'income_change_reason_explanation',
 'expansion_type_employee_increase',
 'expansion_type_net_income_increase',
 'expansion_type_new_assets',
 'expansion_type_inventory_increase',
 'expansion_type_customer_increase',
 'expansion_type_other',
 'expansion_type_other_specify',
 'employees_count_before',
 'work_hours_per_day_before',
 'work_days_per_week_before',
 'work_months_per_year_before',
 'employees_count_after',
 'work_hours_per_day_after',
 'work_days_per_week_after',
 'work_months_per_year_after',
 'employee_source',
 'employees_from_family',
 'employees_from_outside_family',
 'employees_from_family_bool',
 'employees_from_outside_bool',
 'family_employees_count',
 'family_employees_hours_per_day',
 'family_employees_days_per_week',
 'family_employees_months_per_year',
 'outside_employees_count',
 'outside_employees_hours_per_day',
 'outside_employees_days_per_week',
 'outside_employees_months_per_year',
 'payment_frequency_daily',
 'payment_frequency_weekly',
 'payment_frequency_monthly',
 'customer_choice_trust_in_me',
 'customer_choice_material_quality',
 'customer_choice_unique_services',
 'customer_choice_lower_price',
 'customer_choice_deferred_payment',
 'customer_choice_suitable_location',
 'customer_choice_accessibility',
 'customer_choice_other',
 'profit_spending_healthcare',
 'profit_spending_business_expansion',
 'profit_spending_savings',
 'profit_spending_education',
 'profit_spending_housing',
 'profit_spending_food',
 'profit_spending_other',
 'profit_spending_other_specify',
 'decline_reason_market_access',
 'decline_reason_transportation_lack',
 'decline_reason_security_absence',
 'decline_reason_market_distance',
 'decline_reason_low_prices',
 'decline_reason_transportation_costs',
 'decline_reason_other',
 'independent_workspace_available',
 'workspace_description',
 'product_sales_method',
 'trader_integration_with_adra_businesses',
 'purchased_from_erms_suppliers',
 'erms_purchase_other_specify',
 'trader_selection_quality',
 'trader_selection_trust',
 'trader_selection_unique_products',
 'trader_selection_lower_price',
 'trader_selection_deferred_payment',
 'trader_selection_other',
 'trader_relationship_assessment',
 'traders_purchased_from_us',
 'trader_perception_quality',
 'trader_perception_trust',
 'trader_perception_unique_offerings',
 'trader_perception_lower_price',
 'trader_perception_deferred_payment',
 'trader_perception_other',
 'competitors_exist_in_area',
 'competitors_income_impact',
 'product_sales_method_2',
 'business_client_companies',
 'customer_demographics',
 'customer_purchasing_ability',
 'key_points',
 'awareness_source_neighborhood',
 'awareness_source_social_media',
 'awareness_source_reputation',
 'awareness_source_chance',
 'awareness_source_marketing',
 'market_prices_changed_recent',
 'price_change_percentage',
 'price_change_reason_demand_increase',
 'price_change_reason_supply_decrease',
 'price_change_reason_demand_decrease',
 'price_change_reason_supply_increase',
 'price_change_reason_government_subsidies',
 'price_change_reason_market_access',
 'price_change_reason_security_deterioration',
 'customer_transaction_frequency',
 'interruption_impact_sole_provider',
 'interruption_impact_trust_building',
 'interruption_impact_other']

In [678]:
# Exclude demographic/metadata columns from analysis
demo_cols = ['latitude', 'longitude', 'altitude', 'precision', 
             'survey_date', 'governorate', 'district', 'village', 'respondent_id']

# Get columns to analyze (exclude demographics)
analysis_cols = [col for col in erms_df.columns if col not in demo_cols]

# Identify open-ended columns (high unique ratio, text responses)
open_ended_cols = []
for col in analysis_cols:
    non_null_count = erms_df[col].notna().sum()
    if non_null_count > 0:
        unique_ratio = erms_df[col].nunique() / non_null_count
        # Check if it's object/string type and has high unique ratio
        if erms_df[col].dtype == 'object':
            # If >50% unique values OR average text length > 20 chars, likely open-ended
            avg_length = erms_df[col].dropna().astype(str).str.len().mean()
            if unique_ratio > 0.5 or avg_length > 20:
                open_ended_cols.append(col)

# Identify binary columns (likely multiple response)
binary_cols = []
for col in analysis_cols:
    if col not in open_ended_cols:  # Skip open-ended
        unique_vals = erms_df[col].dropna().unique()
        # Check if column is binary (0/1 or True/False)
        if len(unique_vals) <= 2 and set(unique_vals).issubset({0, 1, '0', '1', True, False}):
            binary_cols.append(col)

# Group binary columns by common prefixes
from collections import defaultdict
mr_groups = defaultdict(list)

for col in binary_cols:
    parts = col.rsplit('_', 1)
    if len(parts) > 1:
        prefix = parts[0]
        mr_groups[prefix].append(col)
    else:
        mr_groups['standalone'].append(col)

# Multiple response columns (binary columns grouped together)
mr_columns = binary_cols

# Single response columns (everything else, excluding open-ended)
sr_columns = [col for col in analysis_cols 
              if col not in binary_cols and col not in open_ended_cols]

# Display results
print("=" * 80)
print("COLUMN CLASSIFICATION ANALYSIS")
print("=" * 80)

print(f"\n🗑️ OPEN-ENDED COLUMNS (TO DROP) ({len(open_ended_cols)} total):")
print("-" * 80)
for col in open_ended_cols:
    unique_ratio = erms_df[col].nunique() / erms_df[col].notna().sum()
    avg_len = erms_df[col].dropna().astype(str).str.len().mean()
    print(f"  - {col}")
    print(f"    (Unique ratio: {unique_ratio:.2%}, Avg length: {avg_len:.0f} chars)")

print(f"\n\n📊 MULTIPLE RESPONSE COLUMNS ({len(mr_columns)} total):")
print("-" * 80)
for prefix, cols in sorted(mr_groups.items()):
    if len(cols) > 1:
        print(f"\n{prefix}:")
        for col in cols:
            print(f"  - {col}")

print(f"\n\n📝 SINGLE RESPONSE COLUMNS ({len(sr_columns)} total):")
print("-" * 80)
for col in sr_columns[:20]:
    unique_count = erms_df[col].nunique()
    print(f"  - {col} ({unique_count} unique values)")
if len(sr_columns) > 20:
    print(f"  ... and {len(sr_columns) - 20} more")

print(f"\n\n✅ SUMMARY:")
print(f"  Open-ended (dropped): {len(open_ended_cols)}")
print(f"  Multiple Response: {len(mr_columns)}")
print(f"  Single Response: {len(sr_columns)}")

# Create the final lists
erms_mr = mr_columns
erms_sr = sr_columns

# Drop open-ended columns from the dataframe
erms_df_clean = erms_df.drop(columns=open_ended_cols)

print(f"\n✓ Created: 'mr_var' and 'sr_var' lists")
print(f"✓ Created: 'erms_df_clean' (without open-ended columns)")
print(f"  Original shape: {erms_df.shape}")
print(f"  Cleaned shape: {erms_df_clean.shape}")

================================================================================
COLUMN CLASSIFICATION ANALYSIS
================================================================================

🗑️ OPEN-ENDED COLUMNS (TO DROP) (10 total):
--------------------------------------------------------------------------------
  - income_sources_option_2
    (Unique ratio: 78.18%, Avg length: 13 chars)
  - income_sources_option_3
    (Unique ratio: 86.96%, Avg length: 14 chars)
  - income_sources_option_4
    (Unique ratio: 100.00%, Avg length: 13 chars)
  - profession_choice_other_specify
    (Unique ratio: 33.33%, Avg length: 25 chars)
  - production_constraints_before_support_explain
    (Unique ratio: 100.00%, Avg length: 51 chars)
  - income_change_reason_explanation
    (Unique ratio: 95.31%, Avg length: 46 chars)
  - expansion_type_other_specify
    (Unique ratio: 100.00%, Avg length: 57 chars)
  - employee_source
    (Unique ratio: 8.16%, Avg length: 21 chars)
  - erms_purchase_other_specify
    (Unique ratio: 71.43%, Avg length: 27 chars)
  - key_points
    (Unique ratio: 0.62%, Avg length: 27 chars)


📊 MULTIPLE RESPONSE COLUMNS (88 total):
--------------------------------------------------------------------------------

awareness_source:
  - awareness_source_neighborhood
  - awareness_source_reputation
  - awareness_source_chance
  - awareness_source_marketing

customer_choice:
  - customer_choice_accessibility
  - customer_choice_other

decline_reason_market:
  - decline_reason_market_access
  - decline_reason_market_distance

decline_reason_transportation:
  - decline_reason_transportation_lack
  - decline_reason_transportation_costs

employees_from_outside:
  - employees_from_outside_family
  - employees_from_outside_bool

geographic_scope:
  - geographic_scope_village
  - geographic_scope_neighborhood
  - geographic_scope_district
  - geographic_scope_governorate

new_services_added:
  - new_services_added_workers
  - new_services_added_materials

payment_frequency:
  - payment_frequency_daily
  - payment_frequency_weekly
  - payment_frequency_monthly

price_change_reason_demand:
  - price_change_reason_demand_increase
  - price_change_reason_demand_decrease

price_change_reason_security:
  - price_change_reason_security_stability
  - price_change_reason_security_deterioration

price_change_reason_supply:
  - price_change_reason_supply_decrease
  - price_change_reason_supply_increase

profit_spending:
  - profit_spending_healthcare
  - profit_spending_savings
  - profit_spending_education
  - profit_spending_housing
  - profit_spending_food
  - profit_spending_other

service_differentiation:
  - service_differentiation_quality
  - service_differentiation_trust
  - service_differentiation_other

trader_perception:
  - trader_perception_quality
  - trader_perception_trust
  - trader_perception_other

trader_selection:
  - trader_selection_quality
  - trader_selection_trust
  - trader_selection_other


📝 SINGLE RESPONSE COLUMNS (39 total):
--------------------------------------------------------------------------------
  - service_craft_type (35 unique values)
  - business_operation_duration (5 unique values)
  - income_sources_option_5 (4 unique values)
  - primary_income_source (128 unique values)
  - added_new_services_after_adra (2 unique values)
  - market_price_changed_2_years (1 unique values)
  - income_change_after_support (3 unique values)
  - employees_count_before (4 unique values)
  - work_hours_per_day_before (10 unique values)
  - work_days_per_week_before (6 unique values)
  - work_months_per_year_before (5 unique values)
  - employees_count_after (7 unique values)
  - work_hours_per_day_after (12 unique values)
  - work_days_per_week_after (7 unique values)
  - work_months_per_year_after (9 unique values)
  - family_employees_count (5 unique values)
  - family_employees_hours_per_day (12 unique values)
  - family_employees_days_per_week (6 unique values)
  - family_employees_months_per_year (8 unique values)
  - outside_employees_count (8 unique values)
  ... and 19 more


✅ SUMMARY:
  Open-ended (dropped): 10
  Multiple Response: 88
  Single Response: 39

✓ Created: 'mr_var' and 'sr_var' lists
✓ Created: 'erms_df_clean' (without open-ended columns)
  Original shape: (320, 146)
  Cleaned shape: (320, 136)

In [679]:
with pd.option_context('display.max_rows', None, 
                        'display.max_columns', None,
                        'display.width', None, 
                        'display.max_colwidth', None):
    display(erms_df_clean.sample(3))

,latitude,longitude,altitude,precision,survey_date,governorate,district,village,respondent_id,service_craft_type,business_operation_duration,income_sources_option_5,primary_income_source,geographic_scope_village,geographic_scope_neighborhood,geographic_scope_district,geographic_scope_governorate,profession_choice_higher_profit,profession_choice_is_my_profession,profession_choice_my_expertise,profession_choice_family_profession,profession_choice_only_provider,profession_choice_goods_scarcity,profession_choice_other,service_differentiation_quality,service_differentiation_unique_offering,service_differentiation_lower_price,service_differentiation_deferred_payment,service_differentiation_suitable_location,service_differentiation_good_service,service_differentiation_trust,service_differentiation_other,added_new_services_after_adra,new_services_added_workers,new_services_added_materials,new_services_added_warehouse_expansion,market_price_changed_2_years,price_change_reason_economic_factors,price_change_reason_exchange_control,price_change_reason_security_stability,income_change_after_support,expansion_type_employee_increase,expansion_type_net_income_increase,expansion_type_new_assets,expansion_type_inventory_increase,expansion_type_customer_increase,expansion_type_other,employees_count_before,work_hours_per_day_before,work_days_per_week_before,work_months_per_year_before,employees_count_after,work_hours_per_day_after,work_days_per_week_after,work_months_per_year_after,employees_from_family,employees_from_outside_family,employees_from_family_bool,employees_from_outside_bool,family_employees_count,family_employees_hours_per_day,family_employees_days_per_week,family_employees_months_per_year,outside_employees_count,outside_employees_hours_per_day,outside_employees_days_per_week,outside_employees_months_per_year,payment_frequency_daily,payment_frequency_weekly,payment_frequency_monthly,customer_choice_trust_in_me,customer_choice_material_quality,customer_choice_unique_services,customer_choice_lower_price,customer_choice_deferred_payment,customer_choice_suitable_location,customer_choice_accessibility,customer_choice_other,profit_spending_healthcare,profit_spending_business_expansion,profit_spending_savings,profit_spending_education,profit_spending_housing,profit_spending_food,profit_spending_other,profit_spending_other_specify,decline_reason_market_access,decline_reason_transportation_lack,decline_reason_security_absence,decline_reason_market_distance,decline_reason_low_prices,decline_reason_transportation_costs,decline_reason_other,independent_workspace_available,workspace_description,product_sales_method,trader_integration_with_adra_businesses,purchased_from_erms_suppliers,trader_selection_quality,trader_selection_trust,trader_selection_unique_products,trader_selection_lower_price,trader_selection_deferred_payment,trader_selection_other,trader_relationship_assessment,traders_purchased_from_us,trader_perception_quality,trader_perception_trust,trader_perception_unique_offerings,trader_perception_lower_price,trader_perception_deferred_payment,trader_perception_other,competitors_exist_in_area,competitors_income_impact,product_sales_method_2,business_client_companies,customer_demographics,customer_purchasing_ability,awareness_source_neighborhood,awareness_source_social_media,awareness_source_reputation,awareness_source_chance,awareness_source_marketing,market_prices_changed_recent,price_change_percentage,price_change_reason_demand_increase,price_change_reason_supply_decrease,price_change_reason_demand_decrease,price_change_reason_supply_increase,price_change_reason_government_subsidies,price_change_reason_market_access,price_change_reason_security_deterioration,customer_transaction_frequency,interruption_impact_sole_provider,interruption_impact_trust_building,interruption_impact_other
104,13.049706,44.902120,94.448792,4.347,2020-12-09,Lahj,Tuban,طهرور,R105,خياطة,4,1,الخياطة,1,1,1,1,0,1,1,0,1,1,0,1,1,1,1,1,1,1,0,نعم,1.0,1.0,0.0,نعم,1,1.0,1.0,في زيادة,1.0,1.0,1.0,0.0,1.0,0.0,1.0,4.0,4.0,9.0,2.0,6.0,7.0,12.0,0.0,0.0,1.0,0.0,1.0,4.0,5.0,9.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1,1,1,1,1,1,1,0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,غرفة,كلاهما,NaN,لا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,زيادة,كلاهما,محلات ملابس,افراد,نعم,1,0,1,0,0.0,زادت,0.25,1.0,1.0,1.0,1.0,0.0,0.0,0.0,بشكل دائم,0,1,0
163,13.126828,45.380795,-4.162323,5.360,2020-12-10,Abyan,Zingibar,سواحل,R164,دلالة وبيع الملابس,6,1,أشغال يدوية (كوروشيه),1,1,1,1,1,1,1,1,0,0,0,1,1,0,1,0,1,1,0,نعم,1.0,1.0,0.0,نعم,1,1.0,0.0,في نقصان,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,1,1,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0,1.0,1.0,نعم,غرفة,كلاهما,NaN,لا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,نقصان,كلاهما,الخياطات,افراد,نعم,1,0,1,0,1.0,زادت,1.00,1.0,1.0,1.0,0.0,0.0,0.0,0.0,بشكل دائم,0,1,0
150,13.121028,44.850880,115.945915,4.900,2020-12-10,Lahj,Tuban,الخداد,R151,دلالة وبيع الملابس,4,1,الخياطه,1,0,0,0,1,0,1,0,0,0,0,1,0,1,1,1,0,0,0,نعم,0.0,1.0,0.0,نعم,0,1.0,0.0,في نقصان,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,لا,NaN,كلاهما,NaN,لا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,نعم,نقصان,تجزئة,لا يوجد فقط افراد,افراد,نعم,0,0,1,0,0.0,زادت,1.00,1.0,0.0,0.0,0.0,0.0,0.0,1.0,بشكل شهري,0,1,0

In [680]:
with pd.option_context('display.max_rows', None, 
                        'display.max_columns', None,
                        'display.width', None, 
                        'display.max_colwidth', None):
    display(erms_df[erms_mr].sample(2))

,geographic_scope_village,geographic_scope_neighborhood,geographic_scope_district,geographic_scope_governorate,profession_choice_higher_profit,profession_choice_is_my_profession,profession_choice_my_expertise,profession_choice_family_profession,profession_choice_only_provider,profession_choice_goods_scarcity,profession_choice_other,service_differentiation_quality,service_differentiation_unique_offering,service_differentiation_lower_price,service_differentiation_deferred_payment,service_differentiation_suitable_location,service_differentiation_good_service,service_differentiation_trust,service_differentiation_other,new_services_added_workers,new_services_added_materials,new_services_added_warehouse_expansion,price_change_reason_economic_factors,price_change_reason_exchange_control,price_change_reason_security_stability,expansion_type_employee_increase,expansion_type_net_income_increase,expansion_type_new_assets,expansion_type_inventory_increase,expansion_type_customer_increase,expansion_type_other,employees_from_family,employees_from_outside_family,employees_from_family_bool,employees_from_outside_bool,payment_frequency_daily,payment_frequency_weekly,payment_frequency_monthly,customer_choice_trust_in_me,customer_choice_material_quality,customer_choice_unique_services,customer_choice_lower_price,customer_choice_deferred_payment,customer_choice_suitable_location,customer_choice_accessibility,customer_choice_other,profit_spending_healthcare,profit_spending_business_expansion,profit_spending_savings,profit_spending_education,profit_spending_housing,profit_spending_food,profit_spending_other,profit_spending_other_specify,decline_reason_market_access,decline_reason_transportation_lack,decline_reason_security_absence,decline_reason_market_distance,decline_reason_low_prices,decline_reason_transportation_costs,decline_reason_other,trader_selection_quality,trader_selection_trust,trader_selection_unique_products,trader_selection_lower_price,trader_selection_deferred_payment,trader_selection_other,trader_perception_quality,trader_perception_trust,trader_perception_unique_offerings,trader_perception_lower_price,trader_perception_deferred_payment,trader_perception_other,awareness_source_neighborhood,awareness_source_social_media,awareness_source_reputation,awareness_source_chance,awareness_source_marketing,price_change_reason_demand_increase,price_change_reason_supply_decrease,price_change_reason_demand_decrease,price_change_reason_supply_increase,price_change_reason_government_subsidies,price_change_reason_market_access,price_change_reason_security_deterioration,interruption_impact_sole_provider,interruption_impact_trust_building,interruption_impact_other
176,1,1,0,0,1,1,1,0,0,0,0,1,0,1,1,0,1,1,0,0.0,1.0,0.0,1,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,1,1,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
308,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0.0,1.0,0.0,0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,1,0

In [681]:
erms_sr.remove('primary_income_source')
print(erms_sr)

['service_craft_type', 'business_operation_duration', 'income_sources_option_5', 'added_new_services_after_adra', 'market_price_changed_2_years', 'income_change_after_support', 'employees_count_before', 'work_hours_per_day_before', 'work_days_per_week_before', 'work_months_per_year_before', 'employees_count_after', 'work_hours_per_day_after', 'work_days_per_week_after', 'work_months_per_year_after', 'family_employees_count', 'family_employees_hours_per_day', 'family_employees_days_per_week', 'family_employees_months_per_year', 'outside_employees_count', 'outside_employees_hours_per_day', 'outside_employees_days_per_week', 'outside_employees_months_per_year', 'independent_workspace_available', 'workspace_description', 'product_sales_method', 'trader_integration_with_adra_businesses', 'purchased_from_erms_suppliers', 'trader_relationship_assessment', 'traders_purchased_from_us', 'competitors_exist_in_area', 'competitors_income_impact', 'product_sales_method_2', 'business_client_companies', 'customer_demographics', 'customer_purchasing_ability', 'market_prices_changed_recent', 'price_change_percentage', 'customer_transaction_frequency']

In [682]:

# Updated demo variables
erms_demo_var = ['latitude', 'longitude', 'altitude',
 'precision', 'survey_date', 'governorate', 'district',
  'village', 'respondent_id']

  # Create new dataframes for each question type
erms_mr_col = erms_demo_var + erms_mr
erms_sr_col = erms_demo_var + erms_sr

del erms_sr_col[9]

erms_df_mr = erms_df[erms_mr_col]
erms_df_sr = erms_df[erms_sr_col]

print(erms_df_mr.shape)
print(erms_df_sr.shape)

# Melt single response
erms_melted_sr = pd.melt(
    erms_df_sr,
    id_vars=erms_demo_var,
    var_name='question',
    value_name='response'
)

# Melt multiple response
erms_melted_mr = pd.melt(
    erms_df_mr,
    id_vars=erms_demo_var,
    var_name='question',
    value_name='response'
)

print(f"✓ ERMS data for single responses melted successfully!")
print(f"  Original: {erms_df_sr.shape}")
print(f"  Melted: {erms_melted_sr.shape}")  # Fixed: removed 'df_'

print(f'✓ ERMS data for multiple responses melted successfully!')
print(f"  Original: {erms_df_mr.shape}")
print(f"  Melted: {erms_melted_mr.shape}")  # Fixed: removed 'df_'

(320, 97)
(320, 46)
✓ ERMS data for single responses melted successfully!
  Original: (320, 46)
  Melted: (11840, 11)
✓ ERMS data for multiple responses melted successfully!
  Original: (320, 97)
  Melted: (28160, 11)

In [683]:
erms_melted_sr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11840 entries, 0 to 11839
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   latitude       10915 non-null  float64
 1   longitude      10915 non-null  float64
 2   altitude       10915 non-null  float64
 3   precision      10915 non-null  float64
 4   survey_date    11840 non-null  datetime64[ns]
 5   governorate    11840 non-null  object
 6   district       11840 non-null  object
 7   village        11840 non-null  object
 8   respondent_id  11840 non-null  object
 9   question       11840 non-null  object
 10  response       6662 non-null   object
dtypes: datetime64[ns](1), float64(4), object(6)
memory usage: 1017.6+ KB

In [684]:
erms_melted_mr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28160 entries, 0 to 28159
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   latitude       25960 non-null  float64
 1   longitude      25960 non-null  float64
 2   altitude       25960 non-null  float64
 3   precision      25960 non-null  float64
 4   survey_date    28160 non-null  datetime64[ns]
 5   governorate    28160 non-null  object
 6   district       28160 non-null  object
 7   village        28160 non-null  object
 8   respondent_id  28160 non-null  object
 9   question       28160 non-null  object
 10  response       19624 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(5)
memory usage: 2.4+ MB

In [685]:
erms_melted_sr.dropna(inplace=True)
print(erms_melted_sr.shape)
erms_melted_mr.dropna(inplace=True)
print(erms_melted_mr.shape)

(6156, 11)
(18115, 11)

In [686]:
erms_mr_questions = erms_melted_mr['question'].nunique()
erms_sr_questions = erms_melted_sr['question'].nunique()

cust_sr_questions = cust_sr_melted['question'].nunique()
cust_mr_questions = cust_mr_melted['question'].nunique()

print(erms_mr_questions,',', erms_sr_questions,',', cust_sr_questions,',', cust_mr_questions)

87 , 37 , 6 , 13

In [688]:
import os

# Create output directory
output_dir = 'melted_data'
os.makedirs(output_dir, exist_ok=True)

# Export ERMS melted data
erms_melted_sr.to_csv(f'{output_dir}/erms_melted_sr.csv', index=False, encoding='utf-8-sig')
print(f"✓ erms_melted_sr.csv → {output_dir}/")

erms_melted_mr.to_csv(f'{output_dir}/erms_melted_mr.csv', index=False, encoding='utf-8-sig')
print(f"✓ erms_melted_mr.csv → {output_dir}/")

# Export customer melted data (if you have them)
cust_sr_melted.to_csv(f'{output_dir}/cust_sr_melted.csv', index=False, encoding='utf-8-sig')
print(f"✓ cust_sr_melted.csv → {output_dir}/")

cust_mr_melted.to_csv(f'{output_dir}/cust_mr_melted.csv', index=False, encoding='utf-8-sig')
print(f"✓ cust_mr_melted.csv → {output_dir}/")

print(f"\n✅ All files exported to '{output_dir}/' directory")

✓ erms_melted_sr.csv → melted_data/
✓ erms_melted_mr.csv → melted_data/
✓ cust_sr_melted.csv → melted_data/
✓ cust_mr_melted.csv → melted_data/

✅ All files exported to 'melted_data/' directory

In [690]:
import json

notebook_path = 'Clean_and_Explore.ipynb'

# Check if file exists and has content
if os.path.exists(notebook_path) and os.path.getsize(notebook_path) > 0:
    with open(notebook_path, 'r', encoding='utf-8') as f:
        notebook = json.load(f)
    
    total_lines = sum(
        len([l for l in cell['source'] if l.strip()])
        for cell in notebook['cells'] 
        if cell['cell_type'] == 'code'
    )
    
    code_cells = sum(1 for cell in notebook['cells'] if cell['cell_type'] == 'code')
    
    print(f"📊 Total code lines: {total_lines}")
    print(f"📊 Code cells: {code_cells}")
else:
    print("⚠️  Notebook file is empty or doesn't exist. Please save it first (Ctrl+S)!")

⚠️  Notebook file is empty or doesn't exist. Please save it first (Ctrl+S)!